"use client";
import{useEffect,useMemo,useRef,useState}from"react";
export type QualityTier="performance"|"balanced"|"high";
export type SceneQuality={mobile:boolean;dpr:[number,number];shadows:boolean;antialias:boolean;agentLimit:number;customerLimit:number;ambientNpcCount:number;refreshRate:number;targetFps:number;highRefresh:boolean;fps:number;tier:QualityTier;environment:boolean;particles:boolean};
function nearestRefreshRate(value:number){const common=[30,60,75,90,100,120,144,165];let best=60;for(const hz of common)if(Math.abs(hz-value)<Math.abs(best-value))best=hz;return best}
function useDetectedRefreshRate(){const[refreshRate,setRefreshRate]=useState(60);useEffect(()=>{let raf=0,cancelled=false;const stamps:number[]=[];const sample=(time:number)=>{if(cancelled)return;stamps.push(time);if(stamps.length<50){raf=requestAnimationFrame(sample);return}const intervals:number[]=[];for(let i=1;i<stamps.length;i++){const dt=stamps[i]-stamps[i-1];if(dt>4&&dt<40)intervals.push(dt)}if(intervals.length){intervals.sort((a,b)=>a-b);setRefreshRate(nearestRefreshRate(1000/intervals[Math.floor(intervals.length/2)]))}};raf=requestAnimationFrame(sample);return()=>{cancelled=true;cancelAnimationFrame(raf)}},[]);return refreshRate}
function useMeasuredFps(initial:number){const[fps,setFps]=useState(initial),state=useRef({frames:0,start:0,raf:0});useEffect(()=>{let cancelled=false;state.current.start=performance.now();const tick=(now:number)=>{if(cancelled)return;state.current.frames++;const elapsed=now-state.current.start;if(elapsed>=1000){const measured=state.current.frames*1000/elapsed;setFps(v=>Math.round(v*.45+measured*.55));state.current.frames=0;state.current.start=now}state.current.raf=requestAnimationFrame(tick)};state.current.raf=requestAnimationFrame(tick);return()=>{cancelled=true;cancelAnimationFrame(state.current.raf)}},[]);return fps||initial}
export function useSceneQuality():SceneQuality{
 const[mobile,setMobile]=useState(()=>typeof window!=="undefined"&&window.matchMedia("(max-width:700px)").matches),refreshRate=useDetectedRefreshRate(),targetFps=Math.min(120,refreshRate),fps=useMeasuredFps(targetFps);
 useEffect(()=>{const media=window.matchMedia("(max-width:700px)");const sync=()=>setMobile(media.matches);sync();media.addEventListener("change",sync);return()=>media.removeEventListener("change",sync)},[]);
 return useMemo(()=>{const highRefresh=targetFps>=100;let tier:QualityTier=fps<42?"performance":fps<72||(highRefresh&&fps<88)?"balanced":"high";if(typeof document!=="undefined"&&document.hidden)tier="performance";
  if(mobile){const dpr:[number,number]=tier==="performance"?[.9,1.08]:tier==="balanced"?[1,1.2]:highRefresh?[1.08,1.34]:[1.15,1.45];return{mobile:true,dpr,shadows:false,antialias:true,agentLimit:tier==="performance"?4:tier==="balanced"?5:6,customerLimit:tier==="performance"?5:tier==="balanced"?7:8,ambientNpcCount:tier==="performance"?0:1,refreshRate,targetFps,highRefresh,fps,tier,environment:false,particles:tier==="high"}}
  const dpr:[number,number]=tier==="performance"?[1,1.18]:tier==="balanced"?[1.12,1.38]:highRefresh?[1.22,1.52]:[1.3,1.72];return{mobile:false,dpr,shadows:tier!=="performance",antialias:true,agentLimit:tier==="performance"?6:8,customerLimit:tier==="performance"?10:tier==="balanced"?14:16,ambientNpcCount:tier==="performance"?1:2,refreshRate,targetFps,highRefresh,fps,tier,environment:tier==="high",particles:tier==="high"}},[mobile,refreshRate,targetFps,fps]);
}
export function usePageVisibility(){const[visible,setVisible]=useState(()=>typeof document==="undefined"||!document.hidden);useEffect(()=>{const sync=()=>setVisible(!document.hidden);document.addEventListener("visibilitychange",sync);return()=>document.removeEventListener("visibilitychange",sync)},[]);return visible}
