import {Pool} from "pg";
import type{OpsMetrics,OpsPayload,OpsUser}from"./types";
let pool:Pool|null=null;
function db(){const connectionString=process.env.CUSTOMER_OPS_DATABASE_URL;if(!connectionString)return null;if(!pool)pool=new Pool({connectionString,ssl:{rejectUnauthorized:false},connectionTimeoutMillis:7000,max:3});return pool}
const empty:OpsMetrics={totalUsers:0,verifiedUsers:0,newThisWeek:0,active24h:0,subscribers:0,unsubscribed:0,conversionRate:0,revenueIdr:0,plans:{starter:0,lite:0,pro:0,other:0},payments:{paid:0,pending:0,failed:0}};
export async function loadCustomerOps():Promise<OpsPayload>{const client=db();if(!client)return{configured:false,users:[],metrics:empty,fetchedAt:new Date().toISOString()};
const usersSql=`WITH latest_wedding AS(SELECT DISTINCT ON(owner_id)id,owner_id,bride_name,groom_name,wedding_date,updated_at FROM public.weddings ORDER BY owner_id,updated_at DESC NULLS LAST,id DESC),latest_paid AS(SELECT DISTINCT ON(wedding_id)wedding_id,plan,amount_idr,settled_at FROM public.billing_transactions WHERE status='paid' ORDER BY wedding_id,id DESC),latest_tx AS(SELECT DISTINCT ON(wedding_id)wedding_id,plan,status FROM public.billing_transactions ORDER BY wedding_id,id DESC),latest_ent AS(SELECT DISTINCT ON(wedding_id)wedding_id,expires_at FROM public.entitlements ORDER BY wedding_id,id DESC) SELECT au.id,au.email,au.raw_user_meta_data,au.email_confirmed_at,au.confirmed_at,au.created_at,au.last_sign_in_at,u.name public_name,w.bride_name,w.groom_name,w.wedding_date,paid.plan paid_plan,paid.amount_idr,paid.settled_at,tx.status payment_status,ent.expires_at FROM auth.users au LEFT JOIN public.users u ON u.auth_id=au.id::text OR u.email=au.email LEFT JOIN latest_wedding w ON w.owner_id=u.id LEFT JOIN latest_paid paid ON paid.wedding_id=w.id LEFT JOIN latest_tx tx ON tx.wedding_id=w.id LEFT JOIN latest_ent ent ON ent.wedding_id=w.id ORDER BY au.created_at DESC LIMIT 2000`;
const billingSql=`SELECT COUNT(*)FILTER(WHERE status='paid')::int paid,COUNT(*)FILTER(WHERE status='pending')::int pending,COUNT(*)FILTER(WHERE status='failed')::int failed,COALESCE(SUM(amount_idr)FILTER(WHERE status='paid'),0)::bigint revenue FROM public.billing_transactions`;
const[ur,br]=await Promise.all([client.query(usersSql),client.query(billingSql)]);const now=Date.now(),weekAgo=now-604800000;
const users:OpsUser[]=ur.rows.map(r=>{const meta=r.raw_user_meta_data||{},last=r.last_sign_in_at?new Date(r.last_sign_in_at).getTime():0,paid=Boolean(r.paid_plan);return{id:r.id,email:r.email||"No email",name:meta.name||meta.full_name||r.public_name||(r.email?String(r.email).split("@")[0]:"Unnamed User"),verified:Boolean(r.email_confirmed_at||r.confirmed_at),createdAt:new Date(r.created_at).toISOString(),lastSignInAt:r.last_sign_in_at||null,active24h:Boolean(last&&now-last<86400000),plan:paid?String(r.paid_plan).toLowerCase():"unsubscribed",paymentStatus:paid?"paid":(r.payment_status||"none"),amountPaidIdr:r.amount_idr==null?null:Number(r.amount_idr),purchasedAt:r.settled_at||null,expiresAt:r.expires_at||null,weddingTitle:r.bride_name?`${r.bride_name} & ${r.groom_name||""}`.trim():null,weddingDate:r.wedding_date||null}});
const subscribers=users.filter(u=>u.paymentStatus==="paid").length,plans={starter:0,lite:0,pro:0,other:0};users.forEach(u=>{if(u.paymentStatus!=="paid")return;if(u.plan==="starter"||u.plan==="lite"||u.plan==="pro")plans[u.plan]++;else plans.other++});const b=br.rows[0]||{};const metrics:OpsMetrics={totalUsers:users.length,verifiedUsers:users.filter(u=>u.verified).length,newThisWeek:users.filter(u=>new Date(u.createdAt).getTime()>=weekAgo).length,active24h:users.filter(u=>u.active24h).length,subscribers,unsubscribed:Math.max(0,users.length-subscribers),conversionRate:users.length?Math.round(subscribers/users.length*1000)/10:0,revenueIdr:Number(b.revenue)||0,plans,payments:{paid:Number(b.paid)||0,pending:Number(b.pending)||0,failed:Number(b.failed)||0}};return{configured:true,users,metrics,fetchedAt:new Date().toISOString()}}
