"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {ContactShadows,Environment,Html,OrbitControls,RoundedBox} from "@react-three/drei";
import {Suspense,useRef} from "react";
import * as THREE from "three";
type Worker={name:string;role:string;state:string;position:[number,number,number];color:string};
const workers:Worker[]=[
{name:"Niko",role:"Frontend",state:"CODING",position:[-3.3,.45,-1.8],color:"#7c8cff"},
{name:"Mira",role:"QA",state:"TESTING",position:[3.2,.45,-1.8],color:"#59d6a0"},
{name:"Ari",role:"Reviewer",state:"REVIEWING",position:[3.1,.45,2],color:"#e4b85c"}];
export default function OfficeScene(){return <div className="canvasWrap"><Canvas shadows camera={{position:[9,10,11],fov:42}}><Suspense fallback={null}><color attach="background" args={["#0b0e14"]}/><ambientLight intensity={1.5}/><directionalLight castShadow position={[4,9,5]} intensity={2.2}/><Office/><Environment preset="city"/><ContactShadows position={[0,.02,0]} opacity={.55} scale={20} blur={2.5}/><OrbitControls makeDefault target={[0,0,0]} minDistance={8} maxDistance={20} maxPolarAngle={Math.PI/2.25}/></Suspense></Canvas></div>}
function Office(){return <group><Floor/><Zone position={[-3.3,.16,-2]} label="FRONTEND" color="#273252"/><Zone position={[3.2,.16,-2]} label="QA LAB" color="#214438"/><Zone position={[3.2,.16,2]} label="REVIEW" color="#4b3c24"/><Zone position={[-3.3,.16,2]} label="DEPLOY" color="#392c4b"/><Desk position={[-3.3,.55,-2]}/><Desk position={[3.2,.55,-2]}/><MeetingTable position={[3.2,.45,2]}/><Server position={[-3.3,.65,2]}/>{workers.map(w=><Character key={w.name} {...w}/>)}</group>}
function Floor(){return <group><mesh receiveShadow position={[0,-.05,0]}><boxGeometry args={[10,.2,8]}/><meshStandardMaterial color="#151a23" roughness={.8}/></mesh>{[-5,5].map(x=><mesh key={x} position={[x,.7,0]}><boxGeometry args={[.15,1.5,8]}/><meshStandardMaterial color="#252c39"/></mesh>)}</group>}
function Zone({position,label,color}:{position:[number,number,number],label:string,color:string}){return <group position={position}><mesh receiveShadow rotation={[-Math.PI/2,0,0]}><planeGeometry args={[4.2,3.1]}/><meshStandardMaterial color={color} roughness={.9}/></mesh><Html position={[-1.7,.05,-1.25]} transform><div className="zoneLabel">{label}</div></Html></group>}
function Desk({position}:{position:[number,number,number]}){return <group position={position}><RoundedBox castShadow args={[2,.15,.85]} radius={.08}><meshStandardMaterial color="#465064"/></RoundedBox><mesh position={[0,.55,0]} castShadow><boxGeometry args={[.9,.58,.08]}/><meshStandardMaterial color="#101722" emissive="#233654" emissiveIntensity={.6}/></mesh></group>}
function MeetingTable({position}:{position:[number,number,number]}){return <RoundedBox position={position} castShadow args={[2.4,.25,1.2]} radius={.35}><meshStandardMaterial color="#554b3d"/></RoundedBox>}
function Server({position}:{position:[number,number,number]}){return <group position={position}>{[-.55,0,.55].map(x=><RoundedBox key={x} position={[x,0,0]} castShadow args={[.45,1.3,.7]} radius={.05}><meshStandardMaterial color="#252c38" emissive="#3c2b59" emissiveIntensity={.35}/></RoundedBox>)}</group>}
function Character({name,role,state,position,color}:Worker){const ref=useRef<THREE.Group>(null);useFrame(({clock})=>{if(ref.current)ref.current.position.y=Math.sin(clock.elapsedTime*3+position[0])*.035});return <group ref={ref} position={position}><mesh castShadow position={[0,.65,0]}><capsuleGeometry args={[.27,.55,8,16]}/><meshStandardMaterial color={color}/></mesh><mesh castShadow position={[0,1.2,0]}><sphereGeometry args={[.27,20,20]}/><meshStandardMaterial color="#e8b998"/></mesh><Html center position={[0,1.75,0]}><div className="agentLabel"><b>{name}</b><span>{role} · {state}</span></div></Html></group>}
