"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {ContactShadows,Environment,Html,OrbitControls,RoundedBox,Text} from "@react-three/drei";
import {Suspense,useEffect,useMemo,useRef,useState} from "react";
import * as THREE from "three";
type Row={id:string;worker_id:string;worker_name:string;role:string;state:string;message:string;task?:string;created_at:string};
const spots:Record<string,[number,number,number]>={IDLE:[0,0,3.15],READING:[0,0,.4],CODING:[-3.35,0,-1.8],TESTING:[3.25,0,-1.8],REVIEWING:[3.2,0,2],BLOCKED:[0,0,3.15],DONE:[-3.35,0,2]};
export default function OfficeScene(){const[events,setEvents]=useState<Row[]>([]);useEffect(()=>{let live=true;const load=()=>fetch("/api/events",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(live&&Array.isArray(d.events))setEvents(d.events)}).catch(()=>{});load();const id=setInterval(load,2000);return()=>{live=false;clearInterval(id)}},[]);const workers=useMemo(()=>{const s=new Set<string>();return events.filter(e=>!s.has(e.worker_id)&&!!s.add(e.worker_id)).slice(0,8)},[events]);return <div className="canvasWrap"><Canvas shadows dpr={[1,1.75]} camera={{position:[10,10,12],fov:38}}><Suspense fallback={null}><color attach="background" args={["#080b11"]}/><fog attach="fog" args={["#080b11",16,28]}/><ambientLight intensity={.9}/><directionalLight castShadow position={[-5,11,7]} intensity={2.6} shadow-mapSize={[2048,2048]}/><pointLight position={[0,5,-1]} intensity={22} distance={15} color="#8ca8ff"/><Office workers={workers}/><Environment preset="city"/><ContactShadows position={[0,.01,0]} opacity={.55} scale={18} blur={2.2}/><OrbitControls makeDefault target={[0,1,0]} minDistance={8} maxDistance={20} maxPolarAngle={Math.PI/2.15}/></Suspense></Canvas>{workers.length===0&&<div className="emptyWorld"><b>THE OFFICE IS QUIET</b><span>Agents will appear here when Codex starts working.</span></div>}</div>}
function Office({workers}:{workers:Row[]}){return <group><Room/><Workstation p={[-3.4,0,-2]} title="ENGINEERING" glow="#617cff"/><Workstation p={[3.3,0,-2]} title="QA LAB" glow="#53d79b"/><ReviewRoom/><DeployRack/><Lounge/>{workers.map((w,i)=><Person key={w.worker_id} row={w} target={spots[w.state]||spots.READING} shirt={["#526ef5","#23a873","#e5a83d","#a85bd4"][i%4]}/>)}</group>}
function Room(){return <group><mesh receiveShadow position={[0,-.12,0]}><boxGeometry args={[11,.24,8.5]}/><meshStandardMaterial color="#20242b" roughness={.92}/></mesh><mesh receiveShadow position={[0,1.65,-4.2]}><boxGeometry args={[11,3.5,.16]}/><meshStandardMaterial color="#141922"/></mesh><mesh receiveShadow position={[-5.42,1.65,0]}><boxGeometry args={[.16,3.5,8.5]}/><meshStandardMaterial color="#171c24"/></mesh><Text position={[0,3.02,-4.05]} fontSize={.34} color="#d9e2f0" anchorX="center">WEDDING COPILOT · DEV STUDIO</Text>{[-4,-2,0,2,4].map(x=><group key={x} position={[x,2.45,-4]}><mesh><boxGeometry args={[1.15,.55,.08]}/><meshStandardMaterial color="#202a3a" emissive="#37527c" emissiveIntensity={.45}/></mesh><mesh position={[0,-.58,.05]}><boxGeometry args={[.04,.75,.04]}/><meshStandardMaterial color="#323b49"/></mesh></group>)}</group>}
function Workstation({p,title,glow}:{p:[number,number,number];title:string;glow:string}){return <group position={p}><Rug/><Desk/><Chair/><Monitor x={-.43} glow={glow}/><Monitor x={.43} glow={glow}/><Keyboard/><Plant p={[-1.25,0,.25]}/><Text position={[0,2.15,-.35]} fontSize={.18} color="#8d9bb0">{title}</Text></group>}
function Desk(){return <group><RoundedBox castShadow position={[0,.9,0]} args={[2.5,.14,1]} radius={.07}><meshStandardMaterial color="#4b3b30" roughness={.7}/></RoundedBox>{[-1,1].map(x=><mesh castShadow key={x} position={[x,.43,0]}><boxGeometry args={[.09,.86,.75]}/><meshStandardMaterial color="#252a32"/></mesh>)}</group>}
function Monitor({x,glow}:{x:number;glow:string}){return <group position={[x,1.38,-.17]}><RoundedBox castShadow args={[.72,.48,.06]} radius={.04}><meshStandardMaterial color="#10141b"/></RoundedBox><mesh position={[0,0,.035]}><planeGeometry args={[.62,.37]}/><meshStandardMaterial color={glow} emissive={glow} emissiveIntensity={1.1}/></mesh><mesh position={[0,-.38,0]}><boxGeometry args={[.05,.3,.05]}/><meshStandardMaterial color="#242a34"/></mesh></group>}
function Keyboard(){return <mesh castShadow position={[0,1.02,.25]} rotation={[-.15,0,0]}><boxGeometry args={[.75,.04,.26]}/><meshStandardMaterial color="#161b22"/></mesh>}
function Chair(){return <group position={[0,0,.8]}><RoundedBox castShadow position={[0,.65,0]} args={[.7,.12,.7]} radius={.12}><meshStandardMaterial color="#252b35"/></RoundedBox><RoundedBox castShadow position={[0,1.05,.3]} rotation={[-.12,0,0]} args={[.72,.8,.12]} radius={.12}><meshStandardMaterial color="#252b35"/></RoundedBox><mesh position={[0,.32,0]}><cylinderGeometry args={[.05,.05,.55,10]}/><meshStandardMaterial color="#333b48"/></mesh></group>}
function Rug(){return <mesh receiveShadow position={[0,.015,.25]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[3.5,2.6]}/><meshStandardMaterial color="#262c37" roughness={1}/></mesh>}
function ReviewRoom(){return <group position={[3.2,0,2]}><mesh receiveShadow position={[0,.02,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[1.75,32]}/><meshStandardMaterial color="#332d27"/></mesh><RoundedBox castShadow position={[0,.78,0]} args={[2.3,.16,1.1]} radius={.3}><meshStandardMaterial color="#684c38"/></RoundedBox>{[[-1.15,0,0],[1.15,0,0],[0,0,-.78],[0,0,.78]].map((v,i)=><group key={i} position={v as [number,number,number]} rotation={[0,i===0?Math.PI/2:i===1?-Math.PI/2:i===2?0:Math.PI]}><Chair/></group>)}<Text position={[0,1.9,-.4]} fontSize={.18} color="#c6a978">REVIEW ROOM</Text></group>}
function DeployRack(){return <group position={[-3.5,0,2]}>{[-.7,0,.7].map((x,i)=><group key={x} position={[x,0,0]}><RoundedBox castShadow position={[0,1,0]} args={[.55,2,.7]} radius={.06}><meshStandardMaterial color="#151a21"/></RoundedBox>{[.45,.75,1.05,1.35,1.65].map(y=><mesh key={y} position={[0,y,.36]}><boxGeometry args={[.38,.08,.03]}/><meshStandardMaterial color={i%2?"#62d69f":"#8a75ff"} emissive={i%2?"#62d69f":"#8a75ff"} emissiveIntensity={1.4}/></mesh>)}</group>)}<Text position={[0,2.3,0]} fontSize={.18} color="#a999e4">DEPLOY</Text></group>}
function Lounge(){return <group position={[0,0,2.75]}><RoundedBox castShadow position={[0,.42,0]} args={[2.2,.55,.8]} radius={.18}><meshStandardMaterial color="#283141"/></RoundedBox><Plant p={[1.65,0,0]}/><Plant p={[-1.65,0,0]}/><Text position={[0,1.2,0]} fontSize={.14} color="#77879d">IDLE · PLANNING</Text></group>}
function Plant({p}:{p:[number,number,number]}){return <group position={p}><mesh castShadow position={[0,.25,0]}><cylinderGeometry args={[.22,.16,.45,12]}/><meshStandardMaterial color="#44372f"/></mesh>{[-.14,.1,.25].map((x,i)=><mesh castShadow key={i} position={[x,.65,0]} rotation={[0,0,x]}><sphereGeometry args={[.27,12,12]}/><meshStandardMaterial color="#32654b"/></mesh>)}</group>}
function Person({row,target,shirt}:{row:Row;target:[number,number,number];shirt:string}){const g=useRef<THREE.Group>(null),goal=useRef(new THREE.Vector3(...target));useEffect(()=>{goal.current.set(...target)},[target]);useFrame(({clock},d)=>{if(!g.current)return;const dist=g.current.position.distanceTo(goal.current);g.current.position.lerp(goal.current,Math.min(1,d*1.7));const walk=dist>.08?Math.sin(clock.elapsedTime*9)*.35:Math.sin(clock.elapsedTime*2)*.035;const l=g.current.getObjectByName("legL"),r=g.current.getObjectByName("legR"),a=g.current.getObjectByName("armR");if(l)l.rotation.x=walk;if(r)r.rotation.x=-walk;if(a)a.rotation.x=row.state==="CODING"||row.state==="TESTING"?-1.05:-walk});const blocked=row.state==="BLOCKED";return <group ref={g} position={target}><group position={[0,0,0]}><mesh castShadow position={[0,1.35,0]}><sphereGeometry args={[.25,20,20]}/><meshStandardMaterial color="#d8a47f"/></mesh><mesh castShadow position={[0,1.02,0]}><capsuleGeometry args={[.28,.38,8,16]}/><meshStandardMaterial color={blocked?"#d85656":shirt}/></mesh><Limb name="legL" p={[-.14,.48,0]} /><Limb name="legR" p={[.14,.48,0]} /><Limb name="armL" p={[-.36,1.02,0]} arm/><Limb name="armR" p={[.36,1.02,0]} arm/><mesh castShadow position={[0,1.57,-.02]}><sphereGeometry args={[.255,16,16,0,Math.PI*2,0,Math.PI/2.2]}/><meshStandardMaterial color="#29231f"/></mesh><Face/><StatusRing state={row.state}/></group><Html center position={[0,1.95,0]}><div className={"agentLabel "+(blocked?"blocked":"")}><b>{row.worker_name}</b><span>{row.role}</span><i>{row.state}</i><small>{row.message.slice(0,54)}</small></div></Html></group>}
function Limb({name,p,arm=false}:{name:string;p:[number,number,number];arm?:boolean}){return <group name={name} position={p}><mesh castShadow position={[0,-.24,0]}><capsuleGeometry args={[arm?.08:.1,arm?.34:.42,6,10]}/><meshStandardMaterial color={arm?"#d8a47f":"#202633"}/></mesh>{!arm&&<mesh castShadow position={[0,-.52,.06]}><boxGeometry args={[.18,.11,.34]}/><meshStandardMaterial color="#11151c"/></mesh>}</group>}
function Face(){return <group position={[0,1.35,.235]}><mesh position={[-.085,.035,0]}><sphereGeometry args={[.032,10,10]}/><meshBasicMaterial color="#16171a"/></mesh><mesh position={[.085,.035,0]}><sphereGeometry args={[.032,10,10]}/><meshBasicMaterial color="#16171a"/></mesh><mesh position={[0,-.065,.012]} scale={[1,.35,1]}><sphereGeometry args={[.055,10,10]}/><meshBasicMaterial color="#7e4038"/></mesh></group>}
function StatusRing({state}:{state:string}){const color=state==="BLOCKED"?"#ff5f66":state==="DONE"?"#a58aff":state==="TESTING"?"#58dba1":"#6682ff";const ref=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(ref.current){const s=1+Math.sin(clock.elapsedTime*3)*.08;ref.current.scale.setScalar(s)}});return <mesh ref={ref} rotation={[-Math.PI/2,0,0]} position={[0,.025,0]}><ringGeometry args={[.42,.48,32]}/><meshBasicMaterial color={color} transparent opacity={.72}/></mesh>}
