import type{OfficeEvent,WorkerState}from"./types";
const clean=(v:unknown,fallback="")=>String(v??fallback).replace(/\s+/g," ").trim();
const repoName=(p:any)=>clean(p?.repository?.full_name||p?.repo||p?.repository||"Wedding Copilot");
const task=(repo:string,label:string)=>`${repo} · ${label}`.slice(0,500);
const failure=(value:unknown)=>["failure","failed","error","cancelled","canceled","timed_out","action_required","stale"].includes(clean(value).toLowerCase());
const success=(value:unknown)=>["success","succeeded","ready","completed"].includes(clean(value).toLowerCase());
export function normalizeLifecycleEvent(providerRaw:unknown,eventRaw:unknown,p:any):OfficeEvent[]{const provider=clean(providerRaw,"github").toLowerCase(),event=clean(eventRaw||p?.event||p?.type).toLowerCase();if(provider==="vercel")return normalizeVercel(event,p);return normalizeGithub(event,p)}
function normalizeGithub(event:string,p:any):OfficeEvent[]{const repo=repoName(p),source="github" as const;
 if(event==="workflow_run"){const w=p?.workflow_run||p,status=clean(w?.status),conclusion=clean(w?.conclusion),state:WorkerState=status==="completed"?(failure(conclusion)?"BLOCKED":success(conclusion)?"REVIEWING":"IDLE"):status==="in_progress"?"TESTING":"READING";return[{source,workerId:`github-ci:${repo}`,workerName:"GitHub Actions",role:"QA Automation",state,message:state==="BLOCKED"?`CI failed · ${clean(w?.name,"workflow")}`:state==="REVIEWING"?`CI passed · ${clean(w?.name,"workflow")}`:`${clean(w?.name,"workflow")} · ${status||"queued"}`,task:task(repo,clean(w?.head_branch||w?.display_title||"CI"))}]}
 if(event==="check_run"||event==="check_suite"){const c=p?.check_run||p?.check_suite||p,status=clean(c?.status),conclusion=clean(c?.conclusion),state:WorkerState=status==="completed"?(failure(conclusion)?"BLOCKED":"REVIEWING"):"TESTING";return[{source,workerId:`github-checks:${repo}`,workerName:"GitHub Checks",role:"QA Automation",state,message:state==="BLOCKED"?`Checks failed · ${clean(c?.name,"suite")}`:state==="REVIEWING"?"Checks passed · ready for review":"Checks running",task:task(repo,clean(c?.name||c?.head_branch||"checks"))}]}
 if(event==="pull_request"){const pr=p?.pull_request||p,action=clean(p?.action),merged=!!pr?.merged,state:WorkerState=action==="closed"&&merged?"DEPLOYING":action==="closed"?"IDLE":"REVIEWING";return[{source,workerId:`github-review:${repo}`,workerName:"Pull Request",role:"Code Review",state,message:merged?`PR #${pr?.number||p?.number||""} merged · handoff to deploy`:action==="closed"?`PR #${pr?.number||p?.number||""} closed`:`PR #${pr?.number||p?.number||""} ${action||"updated"}`,task:task(repo,clean(pr?.title||"Review"))}]}
 if(event==="push"){const ref=clean(p?.ref).replace("refs/heads/","");return[{source,workerId:`github-push:${repo}`,workerName:"GitHub",role:"Source Control",state:"CODING",message:`Push received${ref?` · ${ref}`:""}`,task:task(repo,clean(p?.head_commit?.message||p?.after||"commit"))}]}
 if(event==="deployment_status"||event==="status"){const d=p?.deployment_status||p,status=clean(d?.state||d?.status),context=clean(p?.context||d?.context),isVercel=/vercel/i.test(context+" "+clean(d?.environment));const state:WorkerState=failure(status)?"BLOCKED":success(status)?"DONE":"DEPLOYING";return[{source:isVercel?"vercel":"github",workerId:`${isVercel?"vercel":"github"}-deploy:${repo}`,workerName:isVercel?"Vercel":"GitHub Deploy",role:"Release Engineer",state,message:state==="DONE"?"Production deployment ready":state==="BLOCKED"?`Deployment ${status||"failed"}`:`Deployment ${status||"building"}`,task:task(repo,clean(d?.environment||p?.target_url||p?.description||"Production"))}]}
 return[]}
function normalizeVercel(event:string,p:any):OfficeEvent[]{const repo=repoName(p)||clean(p?.project?.name,"Wedding Copilot"),name=clean(p?.project?.name||p?.projectName||repo),status=clean(p?.status||p?.deployment?.status||p?.payload?.deployment?.status),kind=event||clean(p?.type),bad=failure(status)||/error|failed|canceled|cancelled/.test(kind),good=success(status)||/succeeded|ready/.test(kind),state:WorkerState=bad?"BLOCKED":good?"DONE":"DEPLOYING";return[{source:"vercel",workerId:`vercel-deploy:${name}`,workerName:"Vercel",role:"Release Engineer",state,message:state==="DONE"?"Deployment ready":state==="BLOCKED"?"Deployment failed":"Building deployment",task:task(name,clean(p?.url||p?.deployment?.url||p?.target||"Production"))}]}
