"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import type {Vec3} from "../visuals/config";

export type ClawModelKey="desk"|"deskCorner"|"chairDesk"|"chairModern"|"computer"|"cabinet"|"coffeeMachine"|"fridge"|"lamp"|"loungeChair"|"sofa"|"smallPlant"|"plant"|"table"|"coffeeTable"|"roundTable"|"bookcase";
export type HQDistrict="engineering"|"qa"|"review"|"deploy"|"lounge"|"kitchen"|"ops-registration"|"ops-checkout"|"ops-subscription"|"ops-waiting";
export type LayoutItem={id:string;model:ClawModelKey;position:Vec3;rotation?:Vec3;scale?:number|Vec3;tint?:string;district:HQDistrict;blocksNavigation?:boolean};
export const MODEL_FOOTPRINT:Record<ClawModelKey,[number,number]>={desk:[2.05,1.15],deskCorner:[2.5,1.55],chairDesk:[.9,.9],chairModern:[.9,.9],computer:[.75,.45],cabinet:[1.8,.8],coffeeMachine:[.65,.5],fridge:[1,1],lamp:[.7,.7],loungeChair:[1.15,1.1],sofa:[2.25,1.05],smallPlant:[.7,.7],plant:[.8,.8],table:[1.8,1],coffeeTable:[1.5,.9],roundTable:[2.15,2.15],bookcase:[1.25,.65]};
const OPS=20;
export const DEFAULT_HQ_LAYOUT:LayoutItem[]=[
{id:"eng-desk-a",model:"desk",position:[-5.2,0,-4.35],scale:1.55,tint:"#6e4930",district:"engineering",blocksNavigation:true},{id:"eng-chair-a",model:"chairDesk",position:[-5.2,0,-2.95],rotation:[0,Math.PI,0],scale:1.12,tint:"#39475c",district:"engineering"},{id:"eng-monitor-a",model:"computer",position:[-5.55,.84,-4.42],scale:1.02,tint:"#455173",district:"engineering",blocksNavigation:false},{id:"eng-monitor-b",model:"computer",position:[-4.85,.84,-4.42],scale:1.02,tint:"#455173",district:"engineering",blocksNavigation:false},
{id:"qa-desk",model:"desk",position:[5.2,0,-4.35],rotation:[0,Math.PI,0],scale:1.55,tint:"#4a5f51",district:"qa",blocksNavigation:true},{id:"qa-chair",model:"chairDesk",position:[5.2,0,-2.95],rotation:[0,Math.PI,0],scale:1.12,tint:"#344b45",district:"qa"},{id:"qa-monitor-a",model:"computer",position:[4.85,.84,-4.35],rotation:[0,Math.PI,0],scale:1.02,tint:"#3a6656",district:"qa",blocksNavigation:false},{id:"qa-monitor-b",model:"computer",position:[5.55,.84,-4.35],rotation:[0,Math.PI,0],scale:1.02,tint:"#3a6656",district:"qa",blocksNavigation:false},
{id:"deploy-console",model:"deskCorner",position:[-5.35,0,3.55],rotation:[0,Math.PI,0],scale:1.25,tint:"#5a456f",district:"deploy",blocksNavigation:true},{id:"deploy-chair",model:"chairDesk",position:[-5.35,0,2.15],rotation:[0,0,0],scale:1.08,tint:"#4a405d",district:"deploy"},{id:"deploy-monitor",model:"computer",position:[-5.15,.82,3.72],rotation:[0,Math.PI,0],scale:1,tint:"#765f9e",district:"deploy",blocksNavigation:false},
{id:"review-table",model:"roundTable",position:[5.25,0,3.25],scale:1.45,tint:"#755033",district:"review",blocksNavigation:true},{id:"review-chair-w",model:"chairModern",position:[3.45,0,3.25],rotation:[0,Math.PI/2,0],scale:1.08,tint:"#48556b",district:"review"},{id:"review-chair-e",model:"chairModern",position:[7.05,0,3.25],rotation:[0,-Math.PI/2,0],scale:1.08,tint:"#48556b",district:"review"},{id:"review-chair-n",model:"chairModern",position:[5.25,0,1.5],rotation:[0,0,0],scale:1.08,tint:"#48556b",district:"review"},
{id:"lounge-sofa",model:"sofa",position:[0,0,4.95],rotation:[0,Math.PI,0],scale:1.38,tint:"#344b70",district:"lounge",blocksNavigation:true},{id:"lounge-chair-l",model:"loungeChair",position:[-1.85,0,3.85],rotation:[0,.62,0],scale:1.12,tint:"#5b4774",district:"lounge"},{id:"lounge-chair-r",model:"loungeChair",position:[1.85,0,3.85],rotation:[0,-.62,0],scale:1.12,tint:"#5b4774",district:"lounge"},{id:"lounge-table",model:"coffeeTable",position:[0,0,3.72],scale:[1.35,1,1.18],tint:"#6e4d33",district:"lounge",blocksNavigation:true},{id:"lounge-lamp",model:"lamp",position:[-2.65,0,5.05],scale:1.05,tint:"#c09a58",district:"lounge"},{id:"library",model:"bookcase",position:[-7.55,0,4.75],rotation:[0,Math.PI/2,0],scale:[1.15,1.65,1.15],tint:"#5a3523",district:"lounge",blocksNavigation:true},
{id:"dev-plant-a",model:"plant",position:[-7.35,0,-5.15],scale:[1.05,1.45,1.05],district:"engineering"},{id:"dev-plant-b",model:"smallPlant",position:[7.35,0,-5.15],scale:[1,1.55,1],district:"qa"},{id:"kitchen-cabinet",model:"cabinet",position:[7.55,0,-.15],rotation:[0,Math.PI/2,0],scale:[1.25,1,1],tint:"#4b535f",district:"kitchen",blocksNavigation:true},{id:"kitchen-coffee",model:"coffeeMachine",position:[7.42,.8,.18],rotation:[0,Math.PI/2,0],scale:.82,tint:"#2d303b",district:"kitchen",blocksNavigation:false},{id:"kitchen-fridge",model:"fridge",position:[7.55,0,-1.55],scale:[.92,1.3,.92],tint:"#58616a",district:"kitchen",blocksNavigation:true},
{id:"ops-reception",model:"deskCorner",position:[OPS-5.7,0,-5.05],rotation:[0,0,0],scale:1.35,tint:"#6b442a",district:"ops-registration",blocksNavigation:true},{id:"ops-reception-chair",model:"chairDesk",position:[OPS-5.7,0,-3.75],rotation:[0,Math.PI,0],scale:1.08,tint:"#414d61",district:"ops-registration"},{id:"ops-reception-monitor",model:"computer",position:[OPS-5.5,.84,-5.18],scale:1,tint:"#56658c",district:"ops-registration",blocksNavigation:false},
{id:"ops-checkout-desk",model:"table",position:[OPS,0,-5.05],scale:[1.45,1.15,1.15],tint:"#765033",district:"ops-checkout",blocksNavigation:true},{id:"ops-checkout-monitor",model:"computer",position:[OPS,.82,-5.08],scale:1,tint:"#8a6f3d",district:"ops-checkout",blocksNavigation:false},
{id:"ops-sub-desk",model:"desk",position:[OPS+5.7,0,5.02],rotation:[0,Math.PI,0],scale:1.4,tint:"#5c4a78",district:"ops-subscription",blocksNavigation:true},{id:"ops-sub-chair",model:"chairDesk",position:[OPS+5.7,0,3.72],rotation:[0,0,0],scale:1.08,tint:"#544a6f",district:"ops-subscription"},{id:"ops-sub-monitor",model:"computer",position:[OPS+5.7,.84,5.08],rotation:[0,Math.PI,0],scale:1,tint:"#8069a6",district:"ops-subscription",blocksNavigation:false},
{id:"ops-waiting-sofa",model:"sofa",position:[OPS-5.7,0,5.05],rotation:[0,Math.PI,0],scale:1.35,tint:"#3c4d68",district:"ops-waiting",blocksNavigation:true},{id:"ops-waiting-chair",model:"loungeChair",position:[OPS-3.85,0,4.85],rotation:[0,-.55,0],scale:1.05,tint:"#4e5a72",district:"ops-waiting"},{id:"ops-plant-l",model:"smallPlant",position:[OPS-8.1,0,5.35],scale:[1,1.55,1],district:"ops-waiting"},{id:"ops-plant-r",model:"smallPlant",position:[OPS+8.1,0,-5.35],scale:[1,1.55,1],district:"ops-subscription"}
];
const KEY="wc-hq-layout-v3",LEGACY_KEY="wc-hq-layout-v2";
const safeParse=(raw:string|null)=>{if(!raw)return null;try{const parsed=JSON.parse(raw);return Array.isArray(parsed)?parsed as LayoutItem[]:null}catch{return null}};
export function useHQLayout(){const[items,setItems]=useState<LayoutItem[]>(DEFAULT_HQ_LAYOUT),[editMode,setEditMode]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null);useEffect(()=>{const saved=safeParse(localStorage.getItem(KEY));if(saved?.length)setItems(saved);else localStorage.removeItem(LEGACY_KEY)},[]);useEffect(()=>{if(typeof window!=="undefined")localStorage.setItem(KEY,JSON.stringify(items))},[items]);const selected=useMemo(()=>items.find(i=>i.id===selectedId)||null,[items,selectedId]);const updateSelected=useCallback((change:(item:LayoutItem)=>LayoutItem)=>setItems(list=>list.map(item=>item.id===selectedId?change(item):item)),[selectedId]);const nudge=useCallback((dx:number,dz:number)=>updateSelected(item=>({...item,position:[item.position[0]+dx,item.position[1],item.position[2]+dz]})),[updateSelected]);const rotate=useCallback((delta:number)=>updateSelected(item=>({...item,rotation:[item.rotation?.[0]||0,(item.rotation?.[1]||0)+delta,item.rotation?.[2]||0]})),[updateSelected]);const reset=useCallback(()=>{setItems(DEFAULT_HQ_LAYOUT);setSelectedId(null);localStorage.removeItem(KEY)},[]);return{items,editMode,setEditMode,selectedId,setSelectedId,selected,nudge,rotate,reset}}
