"use client";
import {Billboard,RoundedBox,Sparkles,Text} from "@react-three/drei";
import {useFrame} from "@react-three/fiber";
import {useEffect,useMemo,useRef,useState,type RefObject} from "react";
import * as THREE from "three";
import {angleDelta,faceAngle,routeBetween} from "../navigation";
import {profileFor,stateColor,type OfficeRow,type Vec3} from "./config";

type LabelVariant="full"|"customer";
export function Agent({row,target,index,selected,onSelect,initialPosition=[0,0,3.45],labelVariant="full",mobile=false}:{row:OfficeRow;target:Vec3;index:number;selected:boolean;onSelect:()=>void;initialPosition?:Vec3;labelVariant?:LabelVariant;mobile?:boolean}){
 const root=useRef<THREE.Group>(null),body=useRef<THREE.Group>(null),path=useRef<THREE.Vector3[]>([]),last=useRef(""),blink=useRef<THREE.Group>(null),goal=useRef(new THREE.Vector3(...target)),frameBudget=useRef(0),pulse=useRef<THREE.Mesh>(null);
 const[hovered,setHovered]=useState(false),profile=useMemo(()=>profileFor(row.worker_id,index),[row.worker_id,index]),detail=!mobile||selected,showLabel=!mobile||selected||hovered;
 useEffect(()=>{goal.current.set(...target);if(!root.current)return;const key=target.join(",");if(key!==last.current){path.current=routeBetween(root.current.position,target);last.current=key}},[target]);
 useEffect(()=>{if(typeof document==="undefined")return;document.body.style.cursor=hovered?"pointer":"default";return()=>{document.body.style.cursor="default"}},[hovered]);
 useFrame(({clock},dt)=>{if(mobile&&!selected){frameBudget.current+=dt;if(frameBudget.current<1/24)return;dt=frameBudget.current;frameBudget.current=0}const g=root.current,b=body.current;if(!g||!b)return;const next=path.current[0]??goal.current,dist=g.position.distanceTo(next),moving=dist>.065,moveEase=1-Math.exp(-dt*5.4),turnEase=1-Math.exp(-dt*7.5);if(moving){const ang=faceAngle(g.position,next);g.rotation.y+=angleDelta(g.rotation.y,ang)*turnEase;g.position.lerp(next,moveEase)}else if(path.current.length)path.current.shift();else{const facing=["CODING","TESTING","DONE"].includes(row.state)?Math.PI:row.state==="REVIEWING"?0:g.rotation.y;g.rotation.y+=angleDelta(g.rotation.y,facing)*(1-Math.exp(-dt*4.2))}const phase=Math.sin(clock.elapsedTime*9+index),typing=Math.sin(clock.elapsedTime*18+index),working=["CODING","TESTING"].includes(row.state)&&!moving,review=row.state==="REVIEWING"&&!moving,done=row.state==="DONE"&&!moving,blocked=row.state==="BLOCKED"&&!moving,reading=row.state==="READING"&&!moving,idle=row.state==="IDLE"&&!moving;const legL=g.getObjectByName("legL"),legR=g.getObjectByName("legR"),armL=g.getObjectByName("armL"),armR=g.getObjectByName("armR");if(legL)legL.rotation.x=moving?phase*.5:working?-.86:0;if(legR)legR.rotation.x=moving?-phase*.5:working?-.86:0;if(armL){armL.rotation.z=0;armL.rotation.x=moving?-phase*.42:working?-1.02+typing*.06:review?-.48+phase*.1:done?-1.4:reading?-.28:blocked?.16:idle?Math.sin(clock.elapsedTime*1.4)*.04:0}if(armR){armR.rotation.z=0;armR.rotation.x=moving?phase*.42:working?-1.02-typing*.06:review?-.78-phase*.1:done?-1.4:reading?-.58:blocked?.16:idle?-Math.sin(clock.elapsedTime*1.4)*.04:0}if(done){if(armL)armL.rotation.z=-.62;if(armR)armR.rotation.z=.62}if(blocked){if(armL)armL.rotation.z=-.22;if(armR)armR.rotation.z=.22}b.position.y=moving?Math.abs(phase)*.025:working?-.17:done?Math.abs(Math.sin(clock.elapsedTime*4.7))*.05:Math.sin(clock.elapsedTime*1.65+index)*.008;b.rotation.z=blocked?Math.sin(clock.elapsedTime*1.9)*.025:done?Math.sin(clock.elapsedTime*3.5)*.02:0;b.rotation.x=working?.065:reading?.02:0;if(blink.current&&detail){const t=(clock.elapsedTime+index*.73)%4.6;blink.current.scale.y=t<.095?.07:1}if(pulse.current){const s=1+Math.sin(clock.elapsedTime*2.8+index)*.055+(selected?.09:0);pulse.current.scale.setScalar(s)}});
 const blocked=row.state==="BLOCKED",working=["CODING","TESTING"].includes(row.state),done=row.state==="DONE",review=row.state==="REVIEWING",reading=row.state==="READING";
 return <group ref={root} position={initialPosition} onClick={e=>{e.stopPropagation();onSelect()}} onPointerOver={e=>{e.stopPropagation();setHovered(true)}} onPointerOut={()=>setHovered(false)}>
  <mesh ref={pulse} rotation={[-Math.PI/2,0,0]} position={[0,.012,0]}><ringGeometry args={[.4,.49,mobile?18:28]}/><meshBasicMaterial color={stateColor(row.state)} transparent opacity={selected?.9:hovered?.72:.48}/></mesh>
  <group ref={body} scale={labelVariant==="customer"?.9:1}>
   <Leg name="legL" x={-.085} skin={profile.skin} trouser={profile.trouser} bottomStyle={profile.bottomStyle}/><Leg name="legR" x={.085} skin={profile.skin} trouser={profile.trouser} bottomStyle={profile.bottomStyle}/>
   {profile.backpack&&detail&&<Backpack color={profile.outfit}/>}<Torso color={blocked?"#d85656":profile.outfit} topStyle={profile.topStyle}/>
   <Arm name="armL" x={-.18} skin={profile.skin} color={profile.outfit} topStyle={profile.topStyle}/><Arm name="armR" x={.18} skin={profile.skin} color={profile.outfit} topStyle={profile.topStyle}/>
   <Head skin={profile.skin} hair={profile.hair} style={profile.hairStyle} state={row.state} blink={blink} glasses={profile.glasses&&detail} headset={(profile.headset||working)&&detail} mobile={mobile}/>
   {working&&<WorkAccessory state={row.state}/>} {review&&<ReviewTablet/>}{reading&&<PlanningCard/>}
   {done&&(!mobile||selected)&&<Sparkles count={mobile?5:10} scale={[1.2,1.5,1]} position={[0,1.05,0]} size={1.7} speed={.4} color="#b8a8ff"/>}
  </group>
  {showLabel&&<AgentBillboard row={row} selected={selected} variant={labelVariant} mobile={mobile}/>} 
 </group>;
}
function Leg({name,x,skin,trouser,bottomStyle}:{name:string;x:number;skin:string;trouser:string;bottomStyle:"pants"|"cuffed"|"shorts"}){return <group name={name} position={[x,.34,0]}>{bottomStyle==="shorts"?<><mesh position={[0,.04,0]}><boxGeometry args={[.12,.16,.13]}/><meshLambertMaterial color={trouser}/></mesh><mesh position={[0,-.075,0]}><boxGeometry args={[.09,.1,.095]}/><meshLambertMaterial color={skin}/></mesh></>:<><mesh><boxGeometry args={[.12,.28,.13]}/><meshLambertMaterial color={trouser}/></mesh>{bottomStyle==="cuffed"&&<mesh position={[0,-.1,0]}><boxGeometry args={[.125,.035,.135]}/><meshLambertMaterial color="#cfd5df"/></mesh>}</>}<mesh position={[0,-.2,.035]}><boxGeometry args={[.13,.08,.2]}/><meshLambertMaterial color="#11151c"/></mesh></group>}
function Torso({color,topStyle}:{color:string;topStyle:"tee"|"hoodie"|"jacket"}){return <group><mesh position={[0,.76,0]}><boxGeometry args={[.38,.42,.22]}/><meshLambertMaterial color={color}/></mesh>{topStyle==="hoodie"&&<mesh position={[0,.94,-.12]} rotation={[.35,0,0]}><torusGeometry args={[.13,.035,6,16,Math.PI]}/><meshLambertMaterial color={color}/></mesh>}{topStyle==="jacket"&&<><mesh position={[0,.76,.115]}><boxGeometry args={[.022,.38,.012]}/><meshLambertMaterial color="#dbe4ff"/></mesh><mesh position={[-.1,.86,.116]} rotation={[0,0,-.5]}><boxGeometry args={[.14,.025,.012]}/><meshLambertMaterial color="#dbe4ff"/></mesh><mesh position={[.1,.86,.116]} rotation={[0,0,.5]}><boxGeometry args={[.14,.025,.012]}/><meshLambertMaterial color="#dbe4ff"/></mesh></>}<mesh position={[0,1.02,0]}><cylinderGeometry args={[.08,.085,.1,8]}/><meshLambertMaterial color="#c99170"/></mesh></group>}
function Arm({name,x,skin,color,topStyle}:{name:string;x:number;skin:string;color:string;topStyle:"tee"|"hoodie"|"jacket"}){return <group name={name} position={[x,.88,0]}><mesh position={[0,-.13,0]}><boxGeometry args={[.1,.28,.11]}/><meshLambertMaterial color={topStyle==="jacket"?"#dbe4ff":color}/></mesh><mesh position={[0,-.31,0]}><sphereGeometry args={[.065,8,8]}/><meshLambertMaterial color={skin}/></mesh></group>}
function Head({skin,hair,style,state,blink,glasses,headset,mobile}:{skin:string;hair:string;style:number;state:string;blink:RefObject<THREE.Group|null>;glasses:boolean;headset:boolean;mobile:boolean}){const sad=state==="BLOCKED",happy=state==="DONE";return <group position={[0,1.22,0]}><mesh><boxGeometry args={[.42,.4,.36]}/><meshLambertMaterial color={skin}/></mesh><Hair color={hair} style={style}/><group ref={blink} position={[0,.035,.186]}><Eye x={-.09} sad={sad}/><Eye x={.09} sad={sad}/></group><mesh position={[0,-.06,.19]} scale={[happy?1.2:1,.33,1]}><sphereGeometry args={[.045,8,8]}/><meshBasicMaterial color={happy?"#a84d45":"#7e4038"}/></mesh>{!mobile&&<><mesh position={[0,.005,.195]} rotation={[Math.PI/2,0,0]}><coneGeometry args={[.025,.05,6]}/><meshLambertMaterial color={skin}/></mesh><Brow x={-.09} sad={sad}/><Brow x={.09} sad={sad}/></>}{glasses&&<Glasses/>}{headset&&<Headset/>}</group>}
function Eye({x,sad}:{x:number;sad:boolean}){return <mesh position={[x,.035,0]} scale={[1,sad?.6:1,1]}><boxGeometry args={[.045,.055,.015]}/><meshBasicMaterial color="#16191e"/></mesh>}
function Brow({x,sad}:{x:number;sad:boolean}){return <mesh position={[x,.105,.19]} rotation={[0,0,x<0?(sad?.2:-.08):(sad?-.2:.08)]}><boxGeometry args={[.09,.014,.012]}/><meshBasicMaterial color="#4b3329"/></mesh>}
function Hair({color,style}:{color:string;style:number}){if(style===1)return <><mesh position={[0,.235,-.01]}><boxGeometry args={[.44,.12,.36]}/><meshLambertMaterial color={color}/></mesh><mesh position={[-.19,.12,.02]}><boxGeometry args={[.08,.22,.3]}/><meshLambertMaterial color={color}/></mesh></>;if(style===2)return <><mesh position={[0,.23,-.01]}><boxGeometry args={[.42,.1,.35]}/><meshLambertMaterial color={color}/></mesh><mesh position={[.08,.34,-.04]}><boxGeometry args={[.2,.16,.24]}/><meshLambertMaterial color={color}/></mesh></>;if(style===3)return <><mesh position={[0,.22,-.02]}><sphereGeometry args={[.25,10,8,0,Math.PI*2,0,Math.PI/2]}/><meshLambertMaterial color={color}/></mesh><mesh position={[.22,.08,0]}><boxGeometry args={[.06,.2,.28]}/><meshLambertMaterial color={color}/></mesh></>;return <mesh position={[0,.235,-.01]}><boxGeometry args={[.42,.11,.35]}/><meshLambertMaterial color={color}/></mesh>}
function Glasses(){return <group position={[0,.05,.195]}>{[-.09,.09].map(x=><mesh key={x} position={[x,0,0]}><torusGeometry args={[.055,.012,6,12]}/><meshBasicMaterial color="#1b2029"/></mesh>)}<mesh><boxGeometry args={[.07,.012,.012]}/><meshBasicMaterial color="#1b2029"/></mesh></group>}
function Headset(){return <group><mesh position={[0,.12,0]} rotation={[0,0,Math.PI/2]}><torusGeometry args={[.24,.022,6,16,Math.PI]}/><meshLambertMaterial color="#11161e"/></mesh>{[-.22,.22].map(x=><mesh key={x} position={[x,.02,0]}><boxGeometry args={[.04,.16,.07]}/><meshLambertMaterial color="#1f2630"/></mesh>)}</group>}
function Backpack({color}:{color:string}){return <group position={[0,.76,-.15]}><mesh><boxGeometry args={[.28,.32,.12]}/><meshLambertMaterial color={color}/></mesh><mesh position={[-.11,0,.07]}><boxGeometry args={[.025,.28,.02]}/><meshLambertMaterial color="#cbd5e1"/></mesh><mesh position={[.11,0,.07]}><boxGeometry args={[.025,.28,.02]}/><meshLambertMaterial color="#cbd5e1"/></mesh></group>}
function WorkAccessory({state}:{state:string}){const color=state==="TESTING"?"#54d99b":"#6682ff";return <group position={[0,.53,.31]} rotation={[-.18,0,0]}><mesh><boxGeometry args={[.45,.025,.27]}/><meshLambertMaterial color="#151a22"/></mesh><mesh position={[0,.19,-.105]} rotation={[-1.18,0,0]}><boxGeometry args={[.45,.3,.025]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={.85}/></mesh></group>}
function ReviewTablet(){return <group position={[0,.67,.31]} rotation={[-.3,0,0]}><mesh><boxGeometry args={[.35,.025,.25]}/><meshLambertMaterial color="#20262f"/></mesh><mesh position={[0,.017,.01]}><planeGeometry args={[.28,.18]}/><meshStandardMaterial color="#efb85d" emissive="#efb85d" emissiveIntensity={.38}/></mesh></group>}
function PlanningCard(){return <group position={[.11,.73,.29]} rotation={[-.48,.2,.08]}><mesh><boxGeometry args={[.24,.016,.32]}/><meshLambertMaterial color="#e8edf2"/></mesh>{[.065,0,-.065].map(y=><mesh key={y} position={[0,.01,y]}><boxGeometry args={[.16,.004,.012]}/><meshBasicMaterial color="#68778a"/></mesh>)}</group>}
function AgentBillboard({row,selected,variant,mobile}:{row:OfficeRow;selected:boolean;variant:LabelVariant;mobile:boolean}){const showSpeech=selected||row.state==="BLOCKED"||row.state==="DONE",name=row.worker_name.length>16?`${row.worker_name.slice(0,14)}…`:row.worker_name,message=row.message.replace(/\s+/g," ").slice(0,mobile?46:78);return <Billboard follow position={[0,1.82,0]}><group>{showSpeech&&<group position={[0,.55,0]}><RoundedBox args={[mobile?2.1:2.8,mobile?.62:.72,.04]} radius={.08}><meshBasicMaterial color="#080d15" transparent opacity={.93}/></RoundedBox><Text position={[0,.08,.03]} fontSize={mobile?.1:.11} maxWidth={mobile?1.85:2.55} textAlign="center" color="#dfe7f2">{message||row.state}</Text></group>}<RoundedBox args={[variant==="customer"?1.5:1.72,.38,.035]} radius={.06}><meshBasicMaterial color="#0a1018" transparent opacity={selected?.96:.82}/></RoundedBox><Text position={[0,.055,.025]} fontSize={.105} color="#eef3f8">{name}</Text><Text position={[0,-.095,.026]} fontSize={.065} color={stateColor(row.state)}>{`${row.state} · ${row.role}`}</Text></group></Billboard>}
