"use client";
import{Billboard,Sparkles,Text}from"@react-three/drei";
import{useFrame}from"@react-three/fiber";
import{useEffect,useMemo,useRef,useState,type RefObject}from"react";
import*as THREE from"three";
import{angleDelta,faceAngle,routeBetween}from"../navigation";
import{characterPhase,profileFor,roleAccent,stateColor,type OfficeRow,type Vec3}from"./config";

type LabelVariant="full"|"customer";
type CharacterProfile=ReturnType<typeof profileFor>;
export type CharacterRefs={body:RefObject<THREE.Group|null>;legL:RefObject<THREE.Group|null>;legR:RefObject<THREE.Group|null>;armL:RefObject<THREE.Group|null>;armR:RefObject<THREE.Group|null>;blink:RefObject<THREE.Group|null>};
type Lod=0|1|2;
const damp=(current:number,target:number,lambda:number,dt:number)=>THREE.MathUtils.damp(current,target,lambda,dt);

export function Agent({row,target,index:_,selected,onSelect,initialPosition=[0,0,3.45],labelVariant="full",mobile=false,effects=true}:{row:OfficeRow;target:Vec3;index:number;selected:boolean;onSelect:()=>void;initialPosition?:Vec3;labelVariant?:LabelVariant;mobile?:boolean;effects?:boolean}){
 const root=useRef<THREE.Group>(null),body=useRef<THREE.Group>(null),legL=useRef<THREE.Group>(null),legR=useRef<THREE.Group>(null),armL=useRef<THREE.Group>(null),armR=useRef<THREE.Group>(null),blink=useRef<THREE.Group>(null),pulse=useRef<THREE.Mesh>(null),path=useRef<THREE.Vector3[]>([]),last=useRef(""),goal=useRef(new THREE.Vector3(...target)),lodClock=useRef(0),arrive=useRef(0);
 const[hovered,setHovered]=useState(false),[lod,setLod]=useState<Lod>(0),profile=useMemo(()=>profileFor(row.worker_id),[row.worker_id]),phaseOffset=useMemo(()=>characterPhase(row.worker_id),[row.worker_id]),accent=roleAccent(row.role,row.state);
 const detail=lod===0||selected,showLabel=selected||hovered||(!mobile&&lod===0);
 useEffect(()=>{goal.current.set(...target);if(!root.current)return;const key=target.join(",");if(key!==last.current){path.current=routeBetween(root.current.position,target);last.current=key;arrive.current=0}},[target]);
 useEffect(()=>{if(typeof document==="undefined")return;document.body.style.cursor=hovered?"pointer":"default";return()=>{document.body.style.cursor="default"}},[hovered]);
 useFrame(({clock,camera},rawDt)=>{
  const dt=Math.min(rawDt,1/30),g=root.current,b=body.current;if(!g)return;
  lodClock.current+=dt;if(lodClock.current>.22){lodClock.current=0;const distance=camera.position.distanceTo(g.position),next=selected?0:distance>(mobile?12:18)?2:distance>(mobile?6.5:9.5)?1:0;if(next!==lod)setLod(next)}
  const next=path.current[0]??goal.current,dist=g.position.distanceTo(next),moving=dist>.065,moveEase=1-Math.exp(-dt*5.4),turnEase=1-Math.exp(-dt*7.5);
  if(moving){arrive.current=0;const ang=faceAngle(g.position,next);g.rotation.y+=angleDelta(g.rotation.y,ang)*turnEase;g.position.lerp(next,moveEase)}else if(path.current.length){path.current.shift()}else{arrive.current=Math.min(1,arrive.current+dt*3.6);const facing=["CODING","TESTING","DONE"].includes(row.state)?Math.PI:row.state==="REVIEWING"?0:g.rotation.y;g.rotation.y+=angleDelta(g.rotation.y,facing)*(1-Math.exp(-dt*4.2))}
  const t=clock.elapsedTime,phase=Math.sin(t*9+phaseOffset),typing=Math.sin(t*18+phaseOffset),settle=arrive.current,working=["CODING","TESTING"].includes(row.state)&&!moving,review=row.state==="REVIEWING"&&!moving,done=row.state==="DONE"&&!moving,blocked=row.state==="BLOCKED"&&!moving,reading=row.state==="READING"&&!moving,idle=row.state==="IDLE"&&!moving;
  const legLT=moving?phase*.5:working?-.86*settle:0,legRT=moving?-phase*.5:working?-.86*settle:0;
  if(legL.current)legL.current.rotation.x=damp(legL.current.rotation.x,legLT,14,dt);if(legR.current)legR.current.rotation.x=damp(legR.current.rotation.x,legRT,14,dt);
  const armLTx=moving?-phase*.42:working?(-1.02+typing*.06)*settle:review?(-.48+phase*.1)*settle:done?-1.4*settle:reading?-.28*settle:blocked?.16*settle:idle?Math.sin(t*1.4+phaseOffset)*.04:0;
  const armRTx=moving?phase*.42:working?(-1.02-typing*.06)*settle:review?(-.78-phase*.1)*settle:done?-1.4*settle:reading?-.58*settle:blocked?.16*settle:idle?-Math.sin(t*1.4+phaseOffset)*.04:0;
  if(armL.current){armL.current.rotation.x=damp(armL.current.rotation.x,armLTx,13,dt);armL.current.rotation.z=damp(armL.current.rotation.z,done?-.62*settle:blocked?-.22*settle:0,11,dt)}
  if(armR.current){armR.current.rotation.x=damp(armR.current.rotation.x,armRTx,13,dt);armR.current.rotation.z=damp(armR.current.rotation.z,done?.62*settle:blocked?.22*settle:0,11,dt)}
  const bodyY=moving?Math.abs(phase)*.025:working?-.17*settle:done?Math.abs(Math.sin(t*4.7+phaseOffset))*.05:Math.sin(t*1.65+phaseOffset)*.008;if(b){b.position.y=damp(b.position.y,bodyY,12,dt);b.rotation.z=damp(b.rotation.z,blocked?Math.sin(t*1.9+phaseOffset)*.025:done?Math.sin(t*3.5+phaseOffset)*.02:0,10,dt);b.rotation.x=damp(b.rotation.x,working?.065*settle:reading?.02*settle:0,10,dt)}
  if(blink.current&&detail){const bt=(t+phaseOffset)%(4.2+(phaseOffset%1.4));blink.current.scale.y=bt<.09?.08:1}if(pulse.current){const s=1+Math.sin(t*2.8+phaseOffset)*.05+(selected?.08:0);pulse.current.scale.setScalar(s)}
 });
 const working=["CODING","TESTING"].includes(row.state),done=row.state==="DONE",refs={body,legL,legR,armL,armR,blink};
 return <group ref={root} position={initialPosition} onClick={e=>{e.stopPropagation();onSelect()}} onPointerOver={e=>{e.stopPropagation();setHovered(true)}} onPointerOut={()=>setHovered(false)}>
  <mesh ref={pulse} rotation={[-Math.PI/2,0,0]} position={[0,.012,0]}><ringGeometry args={[.4,.49,mobile?18:28]}/><meshBasicMaterial color={stateColor(row.state)} transparent opacity={selected?.9:hovered?.72:.42}/></mesh>
  {lod===2?<FarAvatar profile={profile} accent={accent}/>:<CharacterVisual profile={profile} state={row.state} mobile={mobile} refs={refs} showStateProps={lod===0} detail={detail} accent={accent}/>} 
  {done&&selected&&effects&&<Sparkles count={mobile?4:7} scale={[1.15,1.45,1]} position={[0,1.05,0]} size={1.55} speed={.36} color="#b8a8ff"/>}
  {showLabel&&<AgentBillboard row={row} selected={selected} variant={labelVariant} mobile={mobile} accent={accent}/>} 
 </group>;
}

export function CharacterVisual({profile,state,mobile,refs,showStateProps=true,detail=true,accent="#6682ff"}:{profile:CharacterProfile;state:string;mobile:boolean;refs:CharacterRefs;showStateProps?:boolean;detail?:boolean;accent?:string}){
 const working=["CODING","TESTING"].includes(state),blocked=state==="BLOCKED",review=state==="REVIEWING",reading=state==="READING";
 return <group ref={refs.body}>
  <Leg refObj={refs.legL} x={-.085} skin={profile.skin} trouser={profile.trouser} bottomStyle={profile.bottomStyle} mobile={mobile}/><Leg refObj={refs.legR} x={.085} skin={profile.skin} trouser={profile.trouser} bottomStyle={profile.bottomStyle} mobile={mobile}/>
  {profile.backpack&&detail&&<Backpack color={profile.outfit}/>}<Torso color={blocked?"#d85656":profile.outfit} skin={profile.skin} topStyle={profile.topStyle} mobile={mobile} accent={accent}/>
  <Arm refObj={refs.armL} x={-.18} skin={profile.skin} color={profile.outfit} topStyle={profile.topStyle} mobile={mobile}/><Arm refObj={refs.armR} x={.18} skin={profile.skin} color={profile.outfit} topStyle={profile.topStyle} mobile={mobile}/>
  <Head skin={profile.skin} hair={profile.hair} style={profile.hairStyle} state={state} blink={refs.blink} glasses={profile.glasses&&detail} headset={(profile.headset||working)&&detail} mobile={mobile}/>
  {showStateProps&&working&&<WorkAccessory state={state}/>} {showStateProps&&review&&<ReviewTablet/>}{showStateProps&&reading&&<PlanningCard/>}
 </group>;
}
function FarAvatar({profile,accent}:{profile:CharacterProfile;accent:string}){return <group><mesh position={[0,.63,0]}><boxGeometry args={[.34,.74,.2]}/><meshLambertMaterial color={profile.outfit}/></mesh><mesh position={[0,1.18,0]}><boxGeometry args={[.38,.36,.32]}/><meshLambertMaterial color={profile.skin}/></mesh><mesh position={[0,1.39,-.02]}><boxGeometry args={[.4,.09,.32]}/><meshLambertMaterial color={profile.hair}/></mesh><mesh position={[0,.84,.112]}><boxGeometry args={[.18,.025,.015]}/><meshBasicMaterial color={accent}/></mesh></group>}
function Leg({refObj,x,skin,trouser,bottomStyle,mobile}:{refObj:RefObject<THREE.Group|null>;x:number;skin:string;trouser:string;bottomStyle:"pants"|"cuffed"|"shorts";mobile:boolean}){const cast=!mobile;return <group ref={refObj} position={[x,.34,0]}>{bottomStyle==="shorts"?<><mesh castShadow={cast} position={[0,.04,0]}><boxGeometry args={[.12,.16,.13]}/><meshLambertMaterial color={trouser}/></mesh><mesh castShadow={cast} position={[0,-.075,0]}><boxGeometry args={[.09,.1,.095]}/><meshLambertMaterial color={skin}/></mesh></>:<><mesh castShadow={cast}><boxGeometry args={[.12,.28,.13]}/><meshLambertMaterial color={trouser}/></mesh>{bottomStyle==="cuffed"&&<mesh position={[0,-.1,0]}><boxGeometry args={[.125,.035,.135]}/><meshLambertMaterial color="#cfd5df"/></mesh>}</>}<mesh castShadow={cast} position={[0,-.2,.035]}><boxGeometry args={[.13,.08,.2]}/><meshLambertMaterial color="#11151c"/></mesh></group>}
function Torso({color,skin,topStyle,mobile,accent}:{color:string;skin:string;topStyle:"tee"|"hoodie"|"jacket";mobile:boolean;accent:string}){const cast=!mobile;return <group><mesh castShadow={cast} position={[0,.76,0]}><boxGeometry args={[.38,.42,.22]}/><meshLambertMaterial color={color}/></mesh><mesh position={[0,.84,.116]}><boxGeometry args={[.17,.028,.012]}/><meshBasicMaterial color={accent}/></mesh>{topStyle==="hoodie"&&<mesh position={[0,.94,-.12]} rotation={[.35,0,0]}><torusGeometry args={[.13,.035,5,mobile?10:16,Math.PI]}/><meshLambertMaterial color={color}/></mesh>}{topStyle==="jacket"&&<mesh position={[0,.76,.115]}><boxGeometry args={[.022,.38,.012]}/><meshLambertMaterial color="#dbe4ff"/></mesh>}<mesh castShadow={cast} position={[0,1.02,0]}><cylinderGeometry args={[.08,.085,.1,mobile?6:8]}/><meshLambertMaterial color={skin}/></mesh></group>}
function Arm({refObj,x,skin,color,topStyle,mobile}:{refObj:RefObject<THREE.Group|null>;x:number;skin:string;color:string;topStyle:"tee"|"hoodie"|"jacket";mobile:boolean}){const cast=!mobile;return <group ref={refObj} position={[x,.88,0]}><mesh castShadow={cast} position={[0,-.13,0]}><boxGeometry args={[.1,.28,.11]}/><meshLambertMaterial color={topStyle==="jacket"?"#dbe4ff":color}/></mesh><mesh castShadow={cast} position={[0,-.31,0]}><sphereGeometry args={[.065,mobile?6:8,mobile?6:8]}/><meshLambertMaterial color={skin}/></mesh></group>}
function Head({skin,hair,style,state,blink,glasses,headset,mobile}:{skin:string;hair:string;style:number;state:string;blink:RefObject<THREE.Group|null>;glasses:boolean;headset:boolean;mobile:boolean}){const sad=state==="BLOCKED",happy=state==="DONE",cast=!mobile;return <group position={[0,1.22,0]}><mesh castShadow={cast}><boxGeometry args={[.42,.4,.36]}/><meshLambertMaterial color={skin}/></mesh><Hair color={hair} style={style} mobile={mobile}/><group ref={blink} position={[0,.035,.186]}><Eye x={-.09} sad={sad}/><Eye x={.09} sad={sad}/></group><mesh position={[0,-.06,.19]} scale={[happy?1.2:1,.33,1]}><sphereGeometry args={[.045,mobile?6:8,mobile?6:8]}/><meshBasicMaterial color={happy?"#a84d45":"#7e4038"}/></mesh><mesh position={[0,.005,.195]}><boxGeometry args={[.035,.045,.018]}/><meshLambertMaterial color={skin}/></mesh><Brow x={-.09} sad={sad}/><Brow x={.09} sad={sad}/>{glasses&&<Glasses mobile={mobile}/>} {headset&&<Headset mobile={mobile}/>}</group>}
function Eye({x,sad}:{x:number;sad:boolean}){return <mesh position={[x,.035,0]} scale={[1,sad?.6:1,1]}><boxGeometry args={[.045,.055,.015]}/><meshBasicMaterial color="#16191e"/></mesh>}
function Brow({x,sad}:{x:number;sad:boolean}){return <mesh position={[x,.105,.19]} rotation={[0,0,x<0?(sad?.2:-.08):(sad?-.2:.08)]}><boxGeometry args={[.09,.014,.012]}/><meshBasicMaterial color="#4b3329"/></mesh>}
function Hair({color,style,mobile}:{color:string;style:number;mobile:boolean}){if(style===1)return <><mesh position={[0,.235,-.01]}><boxGeometry args={[.44,.12,.36]}/><meshLambertMaterial color={color}/></mesh><mesh position={[-.19,.12,.02]}><boxGeometry args={[.08,.22,.3]}/><meshLambertMaterial color={color}/></mesh></>;if(style===2)return <><mesh position={[0,.23,-.01]}><boxGeometry args={[.42,.1,.35]}/><meshLambertMaterial color={color}/></mesh><mesh position={[.08,.34,-.04]}><boxGeometry args={[.2,.16,.24]}/><meshLambertMaterial color={color}/></mesh></>;if(style===3)return <><mesh position={[0,.22,-.02]}><sphereGeometry args={[.25,mobile?8:10,mobile?6:8,0,Math.PI*2,0,Math.PI/2]}/><meshLambertMaterial color={color}/></mesh><mesh position={[.22,.08,0]}><boxGeometry args={[.06,.2,.28]}/><meshLambertMaterial color={color}/></mesh></>;return <mesh position={[0,.235,-.01]}><boxGeometry args={[.42,.11,.35]}/><meshLambertMaterial color={color}/></mesh>}
function Glasses({mobile}:{mobile:boolean}){return <group position={[0,.05,.195]}>{[-.09,.09].map(x=><mesh key={x} position={[x,0,0]}><torusGeometry args={[.055,.012,mobile?4:6,mobile?8:12]}/><meshBasicMaterial color="#1b2029"/></mesh>)}<mesh><boxGeometry args={[.07,.012,.012]}/><meshBasicMaterial color="#1b2029"/></mesh></group>}
function Headset({mobile}:{mobile:boolean}){return <group><mesh position={[0,.12,0]} rotation={[0,0,Math.PI/2]}><torusGeometry args={[.24,.022,mobile?4:6,mobile?10:16,Math.PI]}/><meshLambertMaterial color="#11161e"/></mesh>{[-.22,.22].map(x=><mesh key={x} position={[x,.02,0]}><boxGeometry args={[.04,.16,.07]}/><meshLambertMaterial color="#1f2630"/></mesh>)}</group>}
function Backpack({color}:{color:string}){return <group position={[0,.76,-.15]}><mesh><boxGeometry args={[.28,.32,.12]}/><meshLambertMaterial color={color}/></mesh></group>}
function WorkAccessory({state}:{state:string}){const color=state==="TESTING"?"#54d99b":"#6682ff";return <group position={[0,.53,.31]} rotation={[-.18,0,0]}><mesh><boxGeometry args={[.45,.025,.27]}/><meshLambertMaterial color="#151a22"/></mesh><mesh position={[0,.19,-.105]} rotation={[-1.18,0,0]}><boxGeometry args={[.45,.3,.025]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={.7}/></mesh></group>}
function ReviewTablet(){return <group position={[0,.67,.31]} rotation={[-.3,0,0]}><mesh><boxGeometry args={[.35,.025,.25]}/><meshLambertMaterial color="#20262f"/></mesh><mesh position={[0,.017,.01]}><planeGeometry args={[.28,.18]}/><meshStandardMaterial color="#efb85d" emissive="#efb85d" emissiveIntensity={.32}/></mesh></group>}
function PlanningCard(){return <group position={[.11,.73,.29]} rotation={[-.48,.2,.08]}><mesh><boxGeometry args={[.24,.016,.32]}/><meshLambertMaterial color="#e8edf2"/></mesh></group>}
function AgentBillboard({row,selected,variant,mobile,accent}:{row:OfficeRow;selected:boolean;variant:LabelVariant;mobile:boolean;accent:string}){const y=variant==="customer"?1.75:1.82;return <Billboard position={[0,y,0]} follow lockX={false} lockY={false} lockZ={false}><group scale={selected?1.06:1}><mesh position={[0,.04,-.01]}><planeGeometry args={[mobile?.95:1.15,selected?.42:.34]}/><meshBasicMaterial color="#090e16" transparent opacity={.9}/></mesh><mesh position={[-(mobile?.43:.52),.04,0]}><planeGeometry args={[.025,selected?.42:.34]}/><meshBasicMaterial color={accent}/></mesh><Text position={[0,.1,.01]} fontSize={mobile?.075:.085} color="#eef3fa" maxWidth={mobile?.78:.96}>{row.worker_name}</Text><Text position={[0,-.02,.01]} fontSize={.052} color={accent} maxWidth={mobile?.78:.96}>{row.role}</Text>{selected&&<Text position={[0,-.13,.01]} fontSize={.045} color="#8c9aaf" maxWidth={mobile?.78:.96}>{row.message.slice(0,48)}</Text>}</group></Billboard>}
