"use client";
import {Text} from "@react-three/drei";
import {useFrame} from "@react-three/fiber";
import {useMemo,useRef} from "react";
import * as THREE from "three";
import type{Vec3}from"./config";

export function AmbientNPCs({mobile,count=2}:{mobile:boolean;count?:number}){const actors=[{id:"janitor",label:"AMBIENT · FACILITIES",color:"#4f7b65",path:[[-4.9,0,3.7],[-1.5,0,3.7],[1.2,0,.3],[4.8,0,-3.6],[-4.9,0,-3.6]] as Vec3[]},{id:"runner",label:"AMBIENT · COFFEE RUN",color:"#7b5a4b",path:[[4.65,0,3.45],[2.4,0,.35],[-2.8,0,.35],[-3.7,0,-1.1],[4.65,0,3.45]] as Vec3[]}];return <>{actors.slice(0,count).map((a,i)=><AmbientActor key={a.id} path={a.path} label={a.label} color={a.color} mobile={mobile} phase={i*1.8}/>)}</>}
function AmbientActor({path,color,label,mobile,phase}:{path:Vec3[];color:string;label:string;mobile:boolean;phase:number}){const root=useRef<THREE.Group>(null),index=useRef(1),clockGate=useRef(0),target=useMemo(()=>new THREE.Vector3(...path[1]),[path]);useFrame(({clock},dt)=>{if(mobile){clockGate.current+=dt;if(clockGate.current<1/18)return;dt=clockGate.current;clockGate.current=0}const g=root.current;if(!g)return;target.set(...path[index.current]);const dx=target.x-g.position.x,dz=target.z-g.position.z,dist=Math.hypot(dx,dz);if(dist<.14){index.current=(index.current+1)%path.length;return}const desired=Math.atan2(dx,dz);let delta=desired-g.rotation.y;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;g.rotation.y+=delta*(1-Math.exp(-dt*5));const speed=.55;g.position.x+=dx/dist*speed*dt;g.position.z+=dz/dist*speed*dt;g.position.y=Math.abs(Math.sin(clock.elapsedTime*7+phase))*.018;const l=g.getObjectByName("l"),r=g.getObjectByName("r");if(l)l.rotation.x=Math.sin(clock.elapsedTime*7+phase)*.45;if(r)r.rotation.x=-Math.sin(clock.elapsedTime*7+phase)*.45});return <group ref={root} position={path[0]}><mesh position={[0,.72,0]}><boxGeometry args={[.34,.52,.24]}/><meshLambertMaterial color={color}/></mesh><mesh position={[0,1.12,0]}><sphereGeometry args={[.22,mobile?8:12,mobile?8:12]}/><meshLambertMaterial color="#c7906f"/></mesh><group name="l" position={[-.11,.39,0]}><mesh position={[0,-.2,0]}><boxGeometry args={[.09,.4,.11]}/><meshLambertMaterial color="#252b35"/></mesh></group><group name="r" position={[.11,.39,0]}><mesh position={[0,-.2,0]}><boxGeometry args={[.09,.4,.11]}/><meshLambertMaterial color="#252b35"/></mesh></group>{!mobile&&<Text position={[0,1.48,0]} fontSize={.07} color="#6f7d90">{label}</Text>}</group>}
