"use client";
import{Text}from"@react-three/drei";
import{useFrame}from"@react-three/fiber";
import{useMemo,useRef}from"react";
import*as THREE from"three";
import{CharacterVisual,type CharacterRefs}from"./Agent";
import{angleDelta,faceAngle,routeBetween}from"../navigation";
import{characterPhase,profileFor,roleAccent,type Vec3}from"./config";
export function AmbientNPCs({mobile,count=2}:{mobile:boolean;count?:number}){const actors=[{id:"ambient-facilities",label:"AMBIENT · FACILITIES",path:[[-7.1,0,4.8],[-2.2,0,.2],[2.2,0,.2],[7.1,0,-4.8],[-7.1,0,-4.8]] as Vec3[]},{id:"ambient-coffee",label:"AMBIENT · COFFEE RUN",path:[[6.4,0,.8],[2.4,0,.8],[0,0,-1.2],[-2.8,0,.8],[-5.2,0,-2.2],[6.4,0,.8]] as Vec3[]}];return <>{actors.slice(0,count).map(a=><AmbientActor key={a.id} {...a} mobile={mobile}/>)}</>}
function AmbientActor({id,path,label,mobile}:{id:string;path:Vec3[];label:string;mobile:boolean}){const root=useRef<THREE.Group>(null),body=useRef<THREE.Group>(null),legL=useRef<THREE.Group>(null),legR=useRef<THREE.Group>(null),armL=useRef<THREE.Group>(null),armR=useRef<THREE.Group>(null),blink=useRef<THREE.Group>(null),index=useRef(1),route=useRef<THREE.Vector3[]>([]),profile=useMemo(()=>profileFor(id),[id]),phase=useMemo(()=>characterPhase(id),[id]),refs:CharacterRefs={body,legL,legR,armL,armR,blink},accent=roleAccent(label),lastWaypoint=useRef(-1);
 useFrame(({clock},rawDt)=>{const dt=Math.min(rawDt,1/30),g=root.current;if(!g)return;if(lastWaypoint.current!==index.current||!route.current.length){route.current=routeBetween(g.position,path[index.current]);lastWaypoint.current=index.current;if(!route.current.length){index.current=(index.current+1)%path.length;return}}const next=route.current[0],dx=next.x-g.position.x,dz=next.z-g.position.z,dist=Math.hypot(dx,dz);if(dist<.09){route.current.shift();if(!route.current.length){index.current=(index.current+1)%path.length;lastWaypoint.current=-1}return}const desired=faceAngle(g.position,next);g.rotation.y+=angleDelta(g.rotation.y,desired)*(1-Math.exp(-dt*6));const speed=.58,step=Math.min(dist,speed*dt);g.position.x+=dx/dist*step;g.position.z+=dz/dist*step;const walk=Math.sin(clock.elapsedTime*7+phase);if(body.current)body.current.position.y=Math.abs(walk)*.018;if(legL.current)legL.current.rotation.x=walk*.45;if(legR.current)legR.current.rotation.x=-walk*.45;if(armL.current)armL.current.rotation.x=-walk*.35;if(armR.current)armR.current.rotation.x=walk*.35});
 return <group ref={root} position={path[0]}><CharacterVisual profile={profile} state="IDLE" mobile={mobile} refs={refs} showStateProps={false} detail={!mobile} accent={accent}/>{!mobile&&<Text position={[0,1.62,0]} fontSize={.065} color="#d2d9e4" outlineWidth={.004} outlineColor="#05070b">{label}</Text>}</group>}
