"use client";
import{Billboard,Text}from"@react-three/drei";
import{useFrame}from"@react-three/fiber";
import{useMemo,useRef}from"react";
import*as THREE from"three";
import{CharacterVisual}from"./Agent";
import{characterPhase,profileFor,type Vec3}from"./config";

export function AmbientNPCs({mobile,count=2}:{mobile:boolean;count?:number}){const actors=[{id:"ambient-facilities",label:"AMBIENT · FACILITIES",path:[[-4.9,0,3.7],[-1.5,0,3.7],[1.2,0,.3],[4.8,0,-3.6],[-4.9,0,-3.6]] as Vec3[]},{id:"ambient-coffee",label:"AMBIENT · COFFEE RUN",path:[[4.65,0,3.45],[2.4,0,.35],[-2.8,0,.35],[-3.7,0,-1.1],[4.65,0,3.45]] as Vec3[]}];return <>{actors.slice(0,count).map(a=><AmbientActor key={a.id} id={a.id} path={a.path} label={a.label} mobile={mobile}/>)}</>}
function AmbientActor({id,path,label,mobile}:{id:string;path:Vec3[];label:string;mobile:boolean}){const root=useRef<THREE.Group>(null),body=useRef<THREE.Group>(null),legL=useRef<THREE.Group>(null),legR=useRef<THREE.Group>(null),armL=useRef<THREE.Group>(null),armR=useRef<THREE.Group>(null),blink=useRef<THREE.Group>(null),index=useRef(1),target=useMemo(()=>new THREE.Vector3(...path[1]),[path]),profile=useMemo(()=>profileFor(id),[id]),phase=useMemo(()=>characterPhase(id),[id]);useFrame(({clock},rawDt)=>{const dt=Math.min(rawDt,1/30),g=root.current,b=body.current;if(!g||!b)return;target.set(...path[index.current]);const dx=target.x-g.position.x,dz=target.z-g.position.z,dist=Math.hypot(dx,dz);if(dist<.14){index.current=(index.current+1)%path.length;return}const desired=Math.atan2(dx,dz);let delta=desired-g.rotation.y;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;g.rotation.y+=delta*(1-Math.exp(-dt*5.5));const speed=.55;g.position.x+=dx/dist*speed*dt;g.position.z+=dz/dist*speed*dt;const walk=Math.sin(clock.elapsedTime*8+phase);b.position.y=Math.abs(walk)*.022;if(legL.current)legL.current.rotation.x=walk*.5;if(legR.current)legR.current.rotation.x=-walk*.5;if(armL.current)armL.current.rotation.x=-walk*.42;if(armR.current)armR.current.rotation.x=walk*.42;if(blink.current){const bt=(clock.elapsedTime+phase)%4.8;blink.current.scale.y=bt<.09?.08:1}});const refs={body,legL,legR,armL,armR,blink};return <group ref={root} position={path[0]}><CharacterVisual profile={profile} state="IDLE" mobile={mobile} refs={refs} showStateProps={false}/>{!mobile&&<Billboard position={[0,1.72,0]} follow><Text fontSize={.065} color="#708096">{label}</Text></Billboard>}</group>}
