"use client";
import{Text,useGLTF,useTexture}from"@react-three/drei";
import{Suspense,useLayoutEffect,useMemo,useRef}from"react";
import type{ThreeEvent}from"@react-three/fiber";
import*as THREE from"three";
import{OPS_CENTER_X}from"./CustomerOpsWing";
import{ImmersiveMonitor}from"./ImmersiveMonitor";
import{InteractiveProps}from"./InteractiveProps";
import type{OpsMetrics}from"../../../lib/customer-ops/types";
import type{LayoutItem,ClawModelKey}from"../runtime/layout";
import{DISTRICTS}from"../runtime/districts";
import type{Vec3}from"./config";
const RAW="/api/assets/claw",BASE=`${RAW}/models/furniture`;
const MODELS:Record<ClawModelKey,string>={desk:"desk.glb",deskCorner:"deskCorner.glb",chairDesk:"chairDesk.glb",chairModern:"chairModernCushion.glb",computer:"computerScreen.glb",cabinet:"kitchenCabinet.glb",coffeeMachine:"kitchenCoffeeMachine.glb",fridge:"kitchenFridgeSmall.glb",lamp:"lampRoundFloor.glb",loungeChair:"loungeDesignChair.glb",sofa:"loungeSofa.glb",smallPlant:"plantSmall1.glb",plant:"pottedPlant.glb",table:"table.glb",coffeeTable:"tableCoffee.glb",roundTable:"tableRound.glb",bookcase:"bookcaseClosed.glb"};
export type HQRoom="hq"|"dev"|"ops";
type Activity={coding:boolean;testing:boolean;review:boolean;done:boolean;blocked:boolean;activeCount:number;blockedCount:number;doneCount:number};
type MeshDef={geometry:THREE.BufferGeometry;material:THREE.Material;matrix:THREE.Matrix4};
const groupKey=(item:LayoutItem)=>`${item.model}|${item.tint||""}`;
function itemMatrix(item:LayoutItem){const m=new THREE.Matrix4(),p=new THREE.Vector3(...item.position),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(...(item.rotation||[0,0,0]))),raw=item.scale??1,s=Array.isArray(raw)?new THREE.Vector3(...raw):new THREE.Vector3(raw,raw,raw);return m.compose(p,q,s)}
function FurnitureGroup({items,mobile,editMode,onSelect}:{items:LayoutItem[];mobile:boolean;editMode:boolean;onSelect:(id:string)=>void}){const sample=items[0],path=`${BASE}/${MODELS[sample.model]}`,{scene}=useGLTF(path),refs=useRef<Array<THREE.InstancedMesh|null>>([]);const defs=useMemo<MeshDef[]>(()=>{const tint=sample.tint?new THREE.Color(sample.tint):null;scene.updateMatrixWorld(true);const out:MeshDef[]=[];scene.traverse(child=>{if(!(child as THREE.Mesh).isMesh)return;const mesh=child as THREE.Mesh,mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const material of mats){const cloned=material.clone()as THREE.MeshStandardMaterial;if(tint&&"color"in cloned)cloned.color.lerp(tint,.42);if("roughness"in cloned)cloned.roughness=.72;if("metalness"in cloned)cloned.metalness=.06;out.push({geometry:mesh.geometry,material:cloned,matrix:mesh.matrixWorld.clone()})}});return out},[scene,sample.tint]),matrices=useMemo(()=>items.map(itemMatrix),[items]);useLayoutEffect(()=>{defs.forEach((def,di)=>{const inst=refs.current[di];if(!inst)return;const world=new THREE.Matrix4();for(let i=0;i<matrices.length;i++){world.multiplyMatrices(matrices[i],def.matrix);inst.setMatrixAt(i,world)}inst.instanceMatrix.needsUpdate=true;inst.computeBoundingSphere()})},[defs,matrices]);const click=(e:ThreeEvent<MouseEvent>)=>{if(!editMode||typeof e.instanceId!=="number")return;e.stopPropagation();const item=items[e.instanceId];if(item)onSelect(item.id)};return <>{defs.map((def,i)=><instancedMesh key={`${sample.model}-${i}`} ref={node=>{refs.current[i]=node}} args={[def.geometry,def.material,items.length]} castShadow={!mobile} receiveShadow={!mobile} onClick={click}/>)}</>}
function FurnitureField({layout,mobile,editMode,selectedId,onSelect,room}:{layout:LayoutItem[];mobile:boolean;editMode:boolean;selectedId:string|null;onSelect:(id:string)=>void;room:HQRoom}){const visible=useMemo(()=>room==="hq"?layout:layout.filter(item=>room==="dev"?item.position[0]<8:item.position[0]>=8),[layout,room]),groups=useMemo(()=>{const map=new Map<string,LayoutItem[]>();for(const item of visible){const key=groupKey(item),bucket=map.get(key)||[];bucket.push(item);map.set(key,bucket)}return[...map.values()]},[visible]),selected=visible.find(i=>i.id===selectedId)||null;return <group>{groups.map(items=><FurnitureGroup key={groupKey(items[0])} items={items} mobile={mobile} editMode={editMode} onSelect={onSelect}/>)}{editMode&&selected&&<group position={selected.position}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.025,0]}><ringGeometry args={[.48,.58,28]}/><meshBasicMaterial color="#8fa5ff" transparent opacity={.9}/></mesh><Text position={[0,1.55,0]} fontSize={.1} color="#aebcff">{selected.id.toUpperCase()}</Text></group>}</group>}
function DevShell({activity}:{activity:Activity}){return <group><mesh receiveShadow position={[0,-.12,0]}><boxGeometry args={[11.4,.24,8.8]}/><meshStandardMaterial color="#1d222a" roughness={.98}/></mesh><mesh receiveShadow position={[0,1.72,-4.28]}><boxGeometry args={[11.4,3.65,.18]}/><meshStandardMaterial color="#10161f"/></mesh><mesh receiveShadow position={[-5.6,1.72,0]}><boxGeometry args={[.18,3.65,8.8]}/><meshStandardMaterial color="#121821"/></mesh><mesh receiveShadow position={[5.6,1.72,0]}><boxGeometry args={[.18,3.65,8.8]}/><meshStandardMaterial color="#10151c"/></mesh><Text position={[0,3.14,-4.16]} fontSize={.35} color="#e5ebf5">WEDDING COPILOT · DEV STUDIO</Text><Signal p={[-3.45,2.5,-4.13]} label="ENGINEERING" color={activity.coding?"#6682ff":"#526078"}/><Signal p={[3.35,2.5,-4.13]} label="QA LAB" color={activity.testing?"#58dba1":"#526078"}/><Signal p={[3.2,2.05,3.95]} label="REVIEW" color={activity.review?"#efb85d":"#776552"}/><Signal p={[-3.55,2.05,3.95]} label="DEPLOY" color={activity.done?"#a58aff":"#635a78"}/></group>}
function Signal({p,label,color}:{p:Vec3;label:string;color:string}){return <group position={p}><mesh><boxGeometry args={[1.65,.045,.04]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={1.1}/></mesh><Text position={[0,.2,.03]} fontSize={.12} color={color}>{label}</Text></group>}
function ClawBackdrop(){const texture=useTexture(`${RAW}/backgrounds/office-bg.png`);texture.colorSpace=THREE.SRGBColorSpace;return <group position={[0,1.86,-4.17]}><mesh><planeGeometry args={[2.35,1.32]}/><meshBasicMaterial map={texture} toneMapped={false}/></mesh><mesh position={[0,0,-.025]}><boxGeometry args={[2.5,1.47,.06]}/><meshStandardMaterial color="#1b222c"/></mesh></group>}
function TravelPads({room,onFocus}:{room:HQRoom;onFocus?:(p:Vec3)=>void}){const pads=(room==="ops"?["ops-registration","ops-checkout","ops-subscribers"]:["engineering","qa","review","deploy"]).map(k=>DISTRICTS[k as keyof typeof DISTRICTS]).filter(Boolean);return <>{pads.map(d=><group key={d.id} position={d.center} onClick={e=>{e.stopPropagation();onFocus?.(d.center)}}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.025,0]}><ringGeometry args={[.7,.76,24]}/><meshBasicMaterial color={d.color} transparent opacity={.18}/></mesh><Text position={[0,.08,.55]} rotation={[-Math.PI/2,0,0]} fontSize={.06} color={d.color}>{d.label}</Text></group>)}</>}
function BossCommandRoom({activity,opsMetrics,opsUnlocked,mobile,onFocus}:{activity:Activity;opsMetrics:OpsMetrics|null;opsUnlocked:boolean;mobile:boolean;onFocus?:(p:Vec3)=>void}){const p:Vec3=[OPS_CENTER_X+5.6,0,4.35];return <group><mesh position={[p[0],.015,p[2]]}><boxGeometry args={[3.7,.03,2.25]}/><meshStandardMaterial color="#171e29"/></mesh><Text position={[p[0],2.45,p[2]-.95]} fontSize={.13} color="#c4b8ff">BOSS COMMAND ROOM</Text><ImmersiveMonitor position={[p[0]-.85,1.35,p[2]-.92]} title="ENGINEERING HEALTH" lines={[`${activity.activeCount} ACTIVE`,`${activity.blockedCount} BLOCKED`,`${activity.doneCount} SHIPPED`]} color="#6682ff" mobile={mobile} onFocus={()=>onFocus?.(p)}/><ImmersiveMonitor position={[p[0]+.85,1.35,p[2]-.92]} title="CUSTOMER HEALTH" lines={opsUnlocked&&opsMetrics?[`${opsMetrics.totalUsers} USERS`,`${opsMetrics.subscribers} SUBS`,`REV Rp${Math.round(opsMetrics.revenueIdr/1000)}K`,`CONV ${opsMetrics.conversionRate}%`]:["BOSS MODE LOCKED","CUSTOMER DATA PRIVATE"]} color="#9f8cff" mobile={mobile} onFocus={()=>onFocus?.(p)}/></group>}
export function ClawAssetWorld({activity,mobile,layout,editMode,selectedId,onSelectItem,opsMetrics,opsUnlocked,onFocus,room,eventLines=[]}:{activity:Activity;mobile:boolean;layout:LayoutItem[];editMode:boolean;selectedId:string|null;onSelectItem:(id:string)=>void;opsMetrics:OpsMetrics|null;opsUnlocked:boolean;onFocus?:(p:Vec3)=>void;room:HQRoom;eventLines?:string[]}){const showDev=room!=="ops",showOps=room!=="dev";return <group>{showDev&&<DevShell activity={activity}/>} {showDev&&!mobile&&<Suspense fallback={null}><ClawBackdrop/></Suspense>}<Suspense fallback={null}><FurnitureField layout={layout} mobile={mobile} editMode={editMode} selectedId={selectedId} onSelect={onSelectItem} room={room}/></Suspense>{showDev&&<><ImmersiveMonitor position={[-3.55,1.78,-4.03]} title="ENGINEERING" lines={[activity.coding?"CODING ACTIVE":"READY",activity.blocked?"BLOCKED NEEDS ATTENTION":"PIPELINE HEALTHY"]} color="#6682ff" mobile={mobile} onFocus={()=>onFocus?.(DISTRICTS.engineering.center)}/><ImmersiveMonitor position={[3.55,1.78,-4.03]} title="QA LAB" lines={[activity.testing?"TESTING":"STANDBY",activity.review?"REVIEW QUEUED":"NO QUEUE"]} color="#58dba1" mobile={mobile} onFocus={()=>onFocus?.(DISTRICTS.qa.center)}/><ImmersiveMonitor position={[-4.85,1.65,4.02]} rotation={[0,Math.PI,0]} title="DEPLOY BAY" lines={[activity.done?"SHIP COMPLETE":"WAITING",activity.blocked?"CHECK BLOCKER":"VERCEL READY"]} color="#a58aff" mobile={mobile} onFocus={()=>onFocus?.(DISTRICTS.deploy.center)}/><ImmersiveMonitor position={[0,1.48,4.05]} rotation={[0,Math.PI,0]} title="LIVE EVENT FEED" lines={eventLines.length?eventLines:["NO RECENT EVENTS","OFFICE QUIET"]} color="#67b7ff" mobile={mobile} onFocus={()=>onFocus?.(DISTRICTS.review.center)}/><InteractiveProps mobile={mobile}/></>}{showOps&&<><ImmersiveMonitor position={[OPS_CENTER_X,2,-5.34]} title="CUSTOMER OPS" lines={opsUnlocked&&opsMetrics?[`${opsMetrics.totalUsers} REGISTERED`,`${opsMetrics.subscribers} SUBSCRIBERS`,`${opsMetrics.conversionRate}% CONVERSION`,`PENDING ${opsMetrics.payments.pending}`]:["BOSS MODE LOCKED","PRIVATE CUSTOMER DATA"]} color="#9f8cff" mobile={mobile} onFocus={()=>onFocus?.(DISTRICTS["ops-checkout"].center)}/><BossCommandRoom activity={activity} opsMetrics={opsMetrics} opsUnlocked={opsUnlocked} mobile={mobile} onFocus={onFocus}/></>}<TravelPads room={room} onFocus={onFocus}/></group>}
