"use client";
import{RoundedBox,Text}from"@react-three/drei";
import{Agent}from"./Agent";
import type{OfficeRow,Vec3}from"./config";
import type{OpsMetrics,OpsUser}from"../../../lib/customer-ops/types";
export const OPS_CENTER_X=17;
const local={registered:[-4.65,0,-2.55] as Vec3,nurture:[-4.55,0,2.45] as Vec3,checkout:[0,0,-2.65] as Vec3,subscribed:[4.45,0,2.35] as Vec3,attention:[4.45,0,-2.65] as Vec3};
type OpsZone=keyof typeof local;const zoneOrder:OpsZone[]=["registered","nurture","checkout","subscribed","attention"];const abs=(p:Vec3):Vec3=>[p[0]+OPS_CENTER_X,p[1],p[2]];
function stateFor(u:OpsUser){return u.paymentStatus==="paid"?"DONE":u.paymentStatus==="pending"?"REVIEWING":u.paymentStatus==="failed"?"BLOCKED":u.verified?"READING":"IDLE"}
function zoneFor(u:OpsUser):OpsZone{return u.paymentStatus==="paid"?"subscribed":u.paymentStatus==="pending"?"checkout":u.paymentStatus==="failed"?"attention":u.verified?"nurture":"registered"}
function message(u:OpsUser){return u.paymentStatus==="paid"?`${u.plan.toUpperCase()} subscriber`:u.paymentStatus==="pending"?`Checkout pending · ${u.plan}`:u.paymentStatus==="failed"?"Payment needs attention":u.verified?"Verified · no subscription":"New registration · unverified"}
function spread(base:Vec3,index:number):Vec3{const col=index%2,row=Math.floor(index/2);return[base[0]+(col-.5)*1.42,0,base[2]+(row-.5)*1.15]}
function visibleUsers(users:OpsUser[],limit:number){const buckets:Record<OpsZone,OpsUser[]>={registered:[],nurture:[],checkout:[],subscribed:[],attention:[]};for(const user of users)buckets[zoneFor(user)].push(user);const result:OpsUser[]=[];let row=0;while(result.length<limit){let added=false;for(const zone of zoneOrder){const user=buckets[zone][row];if(user){result.push(user);added=true;if(result.length>=limit)break}}if(!added)break;row++}return result}
export function opsZoneCenter(u:OpsUser):Vec3{return abs(local[zoneFor(u)])}
export function CustomerOpsWing({users,metrics,unlocked,selected,onSelect,mobile,limit,effects=true}:{users:OpsUser[];metrics:OpsMetrics|null;unlocked:boolean;selected:string|null;onSelect:(id:string)=>void;mobile:boolean;limit?:number;effects?:boolean}){const cap=limit??(mobile?8:16),counts:Record<OpsZone,number>={registered:0,nurture:0,checkout:0,subscribed:0,attention:0},visual=visibleUsers(users,cap).map((u,index)=>{const z=zoneFor(u),n=counts[z]++,target=abs(spread(local[z],n)),row:OfficeRow={id:u.id,worker_id:`customer-${u.id}`,worker_name:u.name,role:u.paymentStatus==="paid"?`${u.plan.toUpperCase()} CUSTOMER`:"CUSTOMER",state:stateFor(u),message:message(u),task:u.weddingTitle||undefined,created_at:u.createdAt};return{u,row,target,index}});return <group><group position={[OPS_CENTER_X,0,0]}><Architecture/><Connector mobile={mobile}/><Zone p={local.registered} title="REGISTRATION" subtitle={metrics?`${metrics.totalUsers} users`:"LOCKED"} color="#66b7ff" mobile={mobile}/><Zone p={local.nurture} title="NO SUBSCRIPTION" subtitle={metrics?`${metrics.unsubscribed} users`:"LOCKED"} color="#7b8798" mobile={mobile}/><Zone p={local.checkout} title="CHECKOUT" subtitle={metrics?`${metrics.payments.pending} pending`:"LOCKED"} color="#efb85d" mobile={mobile}/><Zone p={local.subscribed} title="SUBSCRIBERS" subtitle={metrics?`${metrics.subscribers} paid`:"LOCKED"} color="#9f8cff" mobile={mobile}/><Zone p={local.attention} title="ATTENTION" subtitle={metrics?`${metrics.payments.failed} failed`:"LOCKED"} color="#ff636b" mobile={mobile}/><CommandWall metrics={metrics} unlocked={unlocked}/></group>{unlocked&&visual.map(v=><Agent key={v.u.id} row={v.row} target={v.target} index={v.index} selected={selected===v.u.id} onSelect={()=>onSelect(v.u.id)} initialPosition={[OPS_CENTER_X-7.4,0,0]} labelVariant="customer" mobile={mobile} effects={effects}/>)}</group>}
function Architecture(){return <group><mesh receiveShadow position={[0,-.12,0]}><boxGeometry args={[15.6,.24,11.4]}/><meshStandardMaterial color="#1d222a" roughness={.96}/></mesh><mesh receiveShadow position={[0,1.72,-5.58]}><boxGeometry args={[15.6,3.65,.18]}/><meshStandardMaterial color="#10161f"/></mesh><mesh receiveShadow position={[7.7,1.72,0]}><boxGeometry args={[.18,3.65,11.4]}/><meshStandardMaterial color="#10151c"/></mesh><Text position={[0,3.14,-5.46]} fontSize={.34} color="#e5ebf5">WEDDING COPILOT · CUSTOMER OPS</Text><mesh position={[0,2.62,-5.43]}><boxGeometry args={[6.5,.02,.035]}/><meshStandardMaterial color="#9f8cff" emissive="#9f8cff" emissiveIntensity={1.2}/></mesh></group>}
function Connector({mobile}:{mobile:boolean}){return <group position={[-9.55,0,0]}><mesh receiveShadow position={[0,.015,0]}><boxGeometry args={[3.9,.03,2.7]}/><meshStandardMaterial color="#242b35"/></mesh><mesh position={[0,1.5,-1.28]}><boxGeometry args={[3.9,3,.06]}/>{mobile?<meshStandardMaterial color="#243143" transparent opacity={.3}/>:<meshPhysicalMaterial color="#91b9dc" transparent opacity={.13} transmission={.5}/>}</mesh><Text position={[0,2.35,-1.22]} fontSize={.12} color="#9f8cff">CUSTOMER OPS CORRIDOR</Text></group>}
function Zone({p,title,subtitle,color,mobile}:{p:Vec3;title:string;subtitle:string;color:string;mobile:boolean}){return <group position={p}><mesh receiveShadow position={[0,.018,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[1.72,mobile?20:36]}/><meshStandardMaterial color="#1b222c"/></mesh><mesh position={[0,.024,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[1.4,1.52,mobile?24:40]}/><meshBasicMaterial color={color} transparent opacity={.48}/></mesh><Text position={[0,2.15,-.55]} fontSize={.17} color={color}>{title}</Text><Text position={[0,1.9,-.55]} fontSize={.09} color="#8290a4">{subtitle}</Text></group>}
function CommandWall({metrics,unlocked}:{metrics:OpsMetrics|null;unlocked:boolean}){return <group position={[0,1.75,-5.28]}><RoundedBox args={[6.7,1.9,.12]} radius={.08}><meshStandardMaterial color="#0c121a"/></RoundedBox>{unlocked&&metrics?<><Text position={[-2.9,.55,.08]} fontSize={.12} color="#718198">CUSTOMER HEALTH</Text><Text position={[-2.9,.18,.08]} fontSize={.27} color="#edf3fb" anchorX="left">{`${metrics.totalUsers} REGISTERED`}</Text><Text position={[-2.9,-.2,.08]} fontSize={.13} color="#58dba1" anchorX="left">{`${metrics.subscribers} SUBSCRIBERS · ${metrics.conversionRate}% CONVERSION`}</Text><Text position={[1.05,.5,.08]} fontSize={.12} color="#718198" anchorX="left">PLANS</Text><Text position={[1.05,.16,.08]} fontSize={.14} color="#7c8cff" anchorX="left">{`STARTER ${metrics.plans.starter}`}</Text><Text position={[1.05,-.12,.08]} fontSize={.14} color="#50cfa0" anchorX="left">{`LITE ${metrics.plans.lite}`}</Text><Text position={[1.05,-.4,.08]} fontSize={.14} color="#b291ff" anchorX="left">{`PRO ${metrics.plans.pro}`}</Text></>:<><Text position={[0,.2,.08]} fontSize={.23} color="#9f8cff">BOSS MODE LOCKED</Text><Text position={[0,-.2,.08]} fontSize={.1} color="#718198">UNLOCK TO LOAD PRIVATE CUSTOMER DATA</Text></>}</group>}
