"use client";
import {Text} from "@react-three/drei";
import {useFrame} from "@react-three/fiber";
import {useRef,useState} from "react";
import * as THREE from "three";
import type {Vec3} from "./config";
export function InteractiveProps({mobile}:{mobile:boolean}){return <group><DeployConsole position={[-7.25,.02,2.55]} mobile={mobile}/><CoffeeTerminal position={[7.38,.9,.15]} mobile={mobile}/><Jukebox position={[7.35,0,5.15]} mobile={mobile}/></group>}
function DeployConsole({position,mobile}:{position:Vec3;mobile:boolean}){const[active,setActive]=useState(false),mat=useRef<THREE.MeshStandardMaterial>(null);useFrame(({clock})=>{if(mat.current)mat.current.emissiveIntensity=(active?1.25:.35)+Math.sin(clock.elapsedTime*3)*.08});return <group position={position} onClick={e=>{e.stopPropagation();setActive(v=>!v)}}><mesh position={[0,.75,0]}><boxGeometry args={[.75,1.35,.55]}/><meshStandardMaterial color="#171d28" metalness={.2}/></mesh><mesh position={[0,1.05,.29]}><boxGeometry args={[.5,.28,.03]}/><meshStandardMaterial ref={mat} color="#3f315d" emissive="#a58aff" emissiveIntensity={.4}/></mesh><Text position={[0,1.43,.31]} fontSize={.085} color="#d7ccff" outlineWidth={.004} outlineColor="#05070b">DEPLOY</Text>{!mobile&&<Text position={[0,.95,.315]} fontSize={.06} color={active?"#9af4bc":"#d0d8e3"} outlineWidth={.003} outlineColor="#05070b">{active?"CONSOLE ONLINE":"TAP TO WAKE"}</Text>}</group>}
function CoffeeTerminal({position,mobile}:{position:Vec3;mobile:boolean}){const steam=useRef<THREE.Group>(null),[active,setActive]=useState(false);useFrame(({clock})=>{if(steam.current){steam.current.visible=active;steam.current.position.y=.25+(clock.elapsedTime%.9)*.2;steam.current.rotation.y=clock.elapsedTime}});return <group position={position} onClick={e=>{e.stopPropagation();setActive(true);setTimeout(()=>setActive(false),2200)}}><group ref={steam} position={[0,.25,0]}>{[0,1,2].map(i=><mesh key={i} position={[(i-1)*.035,i*.05,0]}><sphereGeometry args={[.025,6,6]}/><meshBasicMaterial color="#dce7f3" transparent opacity={.24}/></mesh>)}</group>{!mobile&&<Text position={[0,.58,.18]} fontSize={.06} color="#edd18f" outlineWidth={.003} outlineColor="#05070b">COFFEE</Text>}</group>}
function Jukebox({position,mobile}:{position:Vec3;mobile:boolean}){const[on,setOn]=useState(false),ring=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(ring.current){const s=1+(on?Math.sin(clock.elapsedTime*4)*.08:0);ring.current.scale.setScalar(s)}});return <group position={position} onClick={e=>{e.stopPropagation();setOn(v=>!v)}}><mesh><boxGeometry args={[.5,1.05,.42]}/><meshStandardMaterial color="#241d2a"/></mesh><mesh ref={ring} position={[0,.18,.22]}><circleGeometry args={[.14,18]}/><meshStandardMaterial color={on?"#9f8cff":"#3b4052"} emissive={on?"#9f8cff":"#000"} emissiveIntensity={on?.9:0}/></mesh>{!mobile&&<Text position={[0,.72,.23]} fontSize={.06} color="#e1e6ee" outlineWidth={.003} outlineColor="#05070b">AMBIENCE</Text>}</group>}
